using System;
using System.Linq;
using System.Text;
using FuncyTown.Generators.Internal;
using FuncyTown.Generators.Models;

namespace FuncyTown.Generators.Emitters;

internal static class AliasTaskExtensionEmitter
{
    public static bool CanEmit(ResultAliasModel model)
    {
        if (HasTypeParameters(model.AliasFullyQualifiedName))
        {
            return false;
        }

        if (string.IsNullOrEmpty(model.ContainingTypeDeclarations))
        {
            return true;
        }

        return IsAccessibleFromNamespace(model.AliasAccessibility)
            && model.ContainingTypeDeclarations
                .Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(static (declaration, index) => new { Declaration = declaration, IsTopLevel = index == 0 })
                .All(static item => IsAccessibleContainingType(item.Declaration, item.IsTopLevel));
    }

    public static bool IsPubliclyVisible(ResultAliasModel model)
    {
        if (!CanEmit(model) || model.AliasAccessibility != "public")
        {
            return false;
        }

        if (string.IsNullOrEmpty(model.ContainingTypeDeclarations))
        {
            return true;
        }

        return model.ContainingTypeDeclarations
            .Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries)
            .All(static declaration => IsPublicContainingType(declaration));
    }

    public static string GetHintName(ResultAliasModel model)
    {
        var baseName = model.HintName.Substring(0, model.HintName.Length - ".g.cs".Length);
        return $"{baseName}.TaskExtensions.g.cs";
    }

    public static string Emit(ResultAliasModel model, ResultAliasFamily family)
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591, CA1034");
        sb.AppendLine();

        if (string.IsNullOrEmpty(model.AliasNamespace))
        {
            EmitExtensionClass(sb, model, family);
            return sb.ToString();
        }

        sb.AppendLine($"namespace {model.AliasNamespace}");
        using (sb.Block())
        {
            EmitExtensionClass(sb, model, family);
        }

        return sb.ToString();
    }

    private static bool IsAccessibleFromNamespace(string accessibility) =>
        accessibility != "private"
        && accessibility != "protected"
        && accessibility != "private protected";

    private static bool IsAccessibleContainingType(string declaration, bool isTopLevel)
    {
        if (HasTypeParameters(declaration))
        {
            return false;
        }

        var modifiers = GetModifiers(declaration);
        var hasPrivate = modifiers.Contains("private");
        var hasProtected = modifiers.Contains("protected");
        var hasInternal = modifiers.Contains("internal");
        var hasPublic = modifiers.Contains("public");

        if (hasPrivate || (hasProtected && !hasInternal))
        {
            return false;
        }

        return hasPublic || hasInternal || isTopLevel;
    }

    private static bool IsPublicContainingType(string declaration)
    {
        return !HasTypeParameters(declaration)
            && GetModifiers(declaration).Contains("public");
    }

    private static bool HasTypeParameters(string declaration)
    {
        return declaration.Contains("<", StringComparison.Ordinal);
    }

    private static void EmitExtensionClass(IndentedStringBuilder sb, ResultAliasModel model, ResultAliasFamily family)
    {
        var className = GetExtensionClassName(model);
        var accessibility = GetExtensionClassAccessibility(model);
        var aliasType = model.AliasFullyQualifiedName;

        sb.AppendLine($"{accessibility} static class {className}");
        using (sb.Block())
        {
            sb.AppendLine($"extension(global::System.Threading.Tasks.Task<{aliasType}> source)");
            using (sb.Block())
            {
                if (model.IsVoidSuccess)
                {
                    EmitVoidExtensions(sb, aliasType, model.ErrorTypeFullyQualifiedName);
                }
                else
                {
                    EmitValueExtensions(sb, aliasType, model.ValueTypeFullyQualifiedName, model.ErrorTypeFullyQualifiedName);
                }

                EmitCrossAliasExtensions(sb, model, family);
            }
        }
    }

    private static string GetExtensionClassName(ResultAliasModel model)
    {
        if (string.IsNullOrEmpty(model.ContainingTypeDeclarations))
        {
            return $"{model.AliasName}TaskExtensions";
        }

        var typePath = model.AliasFullyQualifiedName.Replace("global::", string.Empty);
        if (!string.IsNullOrEmpty(model.AliasNamespace)
            && typePath.StartsWith(model.AliasNamespace + ".", StringComparison.Ordinal))
        {
            typePath = typePath.Substring(model.AliasNamespace.Length + 1);
        }

        return $"{SanitizeIdentifier(typePath)}TaskExtensions";
    }

    private static string GetExtensionClassAccessibility(ResultAliasModel model)
    {
        if (model.AliasAccessibility != "public")
        {
            return "internal";
        }

        if (string.IsNullOrEmpty(model.ContainingTypeDeclarations))
        {
            return "public";
        }

        return model.ContainingTypeDeclarations
            .Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries)
            .All(static declaration => GetModifiers(declaration).Contains("public"))
            ? "public"
            : "internal";
    }

    private static string[] GetModifiers(string declaration)
    {
        var typeKeywordIndex = declaration.IndexOf(" class ", StringComparison.Ordinal);
        if (typeKeywordIndex < 0)
        {
            typeKeywordIndex = declaration.IndexOf(" struct ", StringComparison.Ordinal);
        }

        if (typeKeywordIndex < 0)
        {
            typeKeywordIndex = declaration.IndexOf(" interface ", StringComparison.Ordinal);
        }

        if (typeKeywordIndex < 0)
        {
            typeKeywordIndex = declaration.IndexOf(" record", StringComparison.Ordinal);
        }

        var modifiers = typeKeywordIndex < 0
            ? declaration
            : declaration.Substring(0, typeKeywordIndex);
        return modifiers.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
    }

    private static string SanitizeIdentifier(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            builder.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
        }

        return builder.ToString();
    }

    private static void EmitValueExtensions(
        IndentedStringBuilder sb,
        string aliasType,
        string valueType,
        string errorType)
    {
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Map<TNew>", $"global::System.Func<{valueType}, TNew> selector", "Map", "selector");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Map<TNew>", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<TNew>> selector", "MapAsync", "selector", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Transform<TNew>", $"global::System.Func<{valueType}, TNew> selector", "Map");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Transform<TNew>", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<TNew>> selector", "Map");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Select<TNew>", $"global::System.Func<{valueType}, TNew> selector", "Map");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Select<TNew>", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<TNew>> selector", "Map");

        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Bind", $"global::System.Func<{valueType}, {aliasType}> next", "Bind", "next");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Bind", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<{aliasType}>> next", "BindAsync", "next", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Then", $"global::System.Func<{valueType}, {aliasType}> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Then", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<{aliasType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "AndThen", $"global::System.Func<{valueType}, {aliasType}> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "AndThen", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<{aliasType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "SelectMany", $"global::System.Func<{valueType}, {aliasType}> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "SelectMany", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<{aliasType}>> next", "Bind");

        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Bind<TNew>", $"global::System.Func<{valueType}, global::FuncyTown.Result<TNew, {errorType}>> next", "Bind", "next");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Bind<TNew>", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>> next", "BindAsync", "next", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Then<TNew>", $"global::System.Func<{valueType}, global::FuncyTown.Result<TNew, {errorType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Then<TNew>", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "AndThen<TNew>", $"global::System.Func<{valueType}, global::FuncyTown.Result<TNew, {errorType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "AndThen<TNew>", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "SelectMany<TNew>", $"global::System.Func<{valueType}, global::FuncyTown.Result<TNew, {errorType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "SelectMany<TNew>", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>> next", "Bind");

        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<{valueType}, TNewError>>", "MapError<TNewError>", $"global::System.Func<{errorType}, TNewError> selector", "MapError", "selector");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<{valueType}, TNewError>>", "MapError<TNewError>", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<TNewError>> selector", "MapErrorAsync", "selector", awaitCall: true);
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "MapError", $"global::System.Func<{errorType}, {errorType}> selector", "MapError", "selector");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "MapError", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<{errorType}>> selector", "MapErrorAsync", "selector", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<{valueType}, TNewError>>", "TransformError<TNewError>", $"global::System.Func<{errorType}, TNewError> selector", "MapError");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<{valueType}, TNewError>>", "TransformError<TNewError>", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<TNewError>> selector", "MapError");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "TransformError", $"global::System.Func<{errorType}, {errorType}> selector", "MapError");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "TransformError", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<{errorType}>> selector", "MapError");

        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Recover", $"global::System.Func<{errorType}, {valueType}> fallback", "Recover", "fallback");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Recover", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<{valueType}>> fallback", "RecoverAsync", "fallback", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OrElse", $"global::System.Func<{errorType}, {valueType}> fallback", "Recover");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OrElse", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<{valueType}>> fallback", "Recover");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "RecoverWith", $"global::System.Func<{errorType}, {aliasType}> fallback", "RecoverWith", "fallback");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "RecoverWith", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<{aliasType}>> fallback", "RecoverWithAsync", "fallback", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OrElseThen", $"global::System.Func<{errorType}, {aliasType}> fallback", "RecoverWith");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OrElseThen", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<{aliasType}>> fallback", "RecoverWith");

        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OnSuccess", $"global::System.Action<{valueType}> action", "OnSuccess", "action");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OnSuccess", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task> action", "OnSuccessAsync", "action", awaitCall: true);
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OnFailure", $"global::System.Action<{errorType}> action", "OnFailure", "action");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OnFailure", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task> action", "OnFailureAsync", "action", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "IfSuccessful", $"global::System.Action<{valueType}> action", "OnSuccess");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "IfSuccessful", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task> action", "OnSuccess");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Tap", $"global::System.Action<{valueType}> action", "OnSuccess");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Tap", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task> action", "OnSuccess");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "IfFailed", $"global::System.Action<{errorType}> action", "OnFailure");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "IfFailed", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task> action", "OnFailure");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "TapError", $"global::System.Action<{errorType}> action", "OnFailure");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "TapError", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task> action", "OnFailure");

        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Ensure", $"global::System.Func<{valueType}, bool> predicate, {errorType} error", "Ensure", "predicate, error");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Ensure", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<bool>> predicate, {errorType} error", "EnsureAsync", "predicate, error", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Validate", $"global::System.Func<{valueType}, bool> predicate, {errorType} error", "Ensure");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Validate", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<bool>> predicate, {errorType} error", "Ensure");

        EmitForwardingPair(sb, "global::System.Threading.Tasks.Task<TResult>", "Match<TResult>", $"global::System.Func<{valueType}, TResult> onSuccess, global::System.Func<{errorType}, TResult> onFailure", "Match", "onSuccess, onFailure");
        EmitForwardingPair(sb, "global::System.Threading.Tasks.Task<TResult>", "Match<TResult>", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<TResult>> onSuccess, global::System.Func<{errorType}, global::System.Threading.Tasks.Task<TResult>> onFailure", "MatchAsync", "onSuccess, onFailure", awaitCall: true);
    }

    private static void EmitVoidExtensions(IndentedStringBuilder sb, string aliasType, string errorType)
    {
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Map<TNew>", "global::System.Func<TNew> selector", "Map", "selector");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Map<TNew>", "global::System.Func<global::System.Threading.Tasks.Task<TNew>> selector", "MapAsync", "selector", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Transform<TNew>", "global::System.Func<TNew> selector", "Map");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Transform<TNew>", "global::System.Func<global::System.Threading.Tasks.Task<TNew>> selector", "Map");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Select<TNew>", "global::System.Func<TNew> selector", "Map");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Select<TNew>", "global::System.Func<global::System.Threading.Tasks.Task<TNew>> selector", "Map");

        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Bind", $"global::System.Func<{aliasType}> next", "Bind", "next");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Bind", $"global::System.Func<global::System.Threading.Tasks.Task<{aliasType}>> next", "BindAsync", "next", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Then", $"global::System.Func<{aliasType}> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Then", $"global::System.Func<global::System.Threading.Tasks.Task<{aliasType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "AndThen", $"global::System.Func<{aliasType}> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "AndThen", $"global::System.Func<global::System.Threading.Tasks.Task<{aliasType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "SelectMany", $"global::System.Func<{aliasType}> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "SelectMany", $"global::System.Func<global::System.Threading.Tasks.Task<{aliasType}>> next", "Bind");

        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Bind<TNew>", $"global::System.Func<global::FuncyTown.Result<TNew, {errorType}>> next", "Bind", "next");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Bind<TNew>", $"global::System.Func<global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>> next", "BindAsync", "next", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Then<TNew>", $"global::System.Func<global::FuncyTown.Result<TNew, {errorType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "Then<TNew>", $"global::System.Func<global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "AndThen<TNew>", $"global::System.Func<global::FuncyTown.Result<TNew, {errorType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "AndThen<TNew>", $"global::System.Func<global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "SelectMany<TNew>", $"global::System.Func<global::FuncyTown.Result<TNew, {errorType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>", "SelectMany<TNew>", $"global::System.Func<global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>> next", "Bind");

        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::FuncyTown.Unit, TNewError>>", "MapError<TNewError>", $"global::System.Func<{errorType}, TNewError> selector", "MapError", "selector");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::FuncyTown.Unit, TNewError>>", "MapError<TNewError>", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<TNewError>> selector", "MapErrorAsync", "selector", awaitCall: true);
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "MapError", $"global::System.Func<{errorType}, {errorType}> selector", "MapError", "selector");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "MapError", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<{errorType}>> selector", "MapErrorAsync", "selector", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::FuncyTown.Unit, TNewError>>", "TransformError<TNewError>", $"global::System.Func<{errorType}, TNewError> selector", "MapError");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::FuncyTown.Unit, TNewError>>", "TransformError<TNewError>", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<TNewError>> selector", "MapError");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "TransformError", $"global::System.Func<{errorType}, {errorType}> selector", "MapError");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "TransformError", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<{errorType}>> selector", "MapError");

        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "RecoverWith", $"global::System.Func<{errorType}, {aliasType}> fallback", "RecoverWith", "fallback");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "RecoverWith", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<{aliasType}>> fallback", "RecoverWithAsync", "fallback", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OrElseThen", $"global::System.Func<{errorType}, {aliasType}> fallback", "RecoverWith");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OrElseThen", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task<{aliasType}>> fallback", "RecoverWith");

        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OnSuccess", "global::System.Action action", "OnSuccess", "action");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OnSuccess", "global::System.Func<global::System.Threading.Tasks.Task> action", "OnSuccessAsync", "action", awaitCall: true);
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OnFailure", $"global::System.Action<{errorType}> action", "OnFailure", "action");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "OnFailure", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task> action", "OnFailureAsync", "action", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "IfSuccessful", "global::System.Action action", "OnSuccess");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "IfSuccessful", "global::System.Func<global::System.Threading.Tasks.Task> action", "OnSuccess");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Tap", "global::System.Action action", "OnSuccess");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "Tap", "global::System.Func<global::System.Threading.Tasks.Task> action", "OnSuccess");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "IfFailed", $"global::System.Action<{errorType}> action", "OnFailure");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "IfFailed", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task> action", "OnFailure");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "TapError", $"global::System.Action<{errorType}> action", "OnFailure");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{aliasType}>", "TapError", $"global::System.Func<{errorType}, global::System.Threading.Tasks.Task> action", "OnFailure");

        EmitForwardingPair(sb, "global::System.Threading.Tasks.Task<TResult>", "Match<TResult>", $"global::System.Func<TResult> onSuccess, global::System.Func<{errorType}, TResult> onFailure", "Match", "onSuccess, onFailure");
        EmitForwardingPair(sb, "global::System.Threading.Tasks.Task<TResult>", "Match<TResult>", $"global::System.Func<global::System.Threading.Tasks.Task<TResult>> onSuccess, global::System.Func<{errorType}, global::System.Threading.Tasks.Task<TResult>> onFailure", "MatchAsync", "onSuccess, onFailure", awaitCall: true);
    }

    private static void EmitCrossAliasExtensions(
        IndentedStringBuilder sb,
        ResultAliasModel model,
        ResultAliasFamily family)
    {
        foreach (var sibling in family.Members)
        {
            if (!CrossAliasOverloadEmitter.CanEmit(model, sibling))
            {
                continue;
            }

            if (model.IsVoidSuccess)
            {
                EmitVoidCrossAliasExtensions(sb, sibling.AliasFullyQualifiedName);
            }
            else
            {
                EmitValueCrossAliasExtensions(sb, model.ValueTypeFullyQualifiedName, sibling.AliasFullyQualifiedName);
            }
        }
    }

    private static void EmitValueCrossAliasExtensions(
        IndentedStringBuilder sb,
        string valueType,
        string siblingType)
    {
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "Bind", $"global::System.Func<{valueType}, {siblingType}> next", "Bind", "next");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "Bind", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<{siblingType}>> next", "BindAsync", "next", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "Then", $"global::System.Func<{valueType}, {siblingType}> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "Then", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<{siblingType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "AndThen", $"global::System.Func<{valueType}, {siblingType}> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "AndThen", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<{siblingType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "SelectMany", $"global::System.Func<{valueType}, {siblingType}> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "SelectMany", $"global::System.Func<{valueType}, global::System.Threading.Tasks.Task<{siblingType}>> next", "Bind");
    }

    private static void EmitVoidCrossAliasExtensions(IndentedStringBuilder sb, string siblingType)
    {
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "Bind", $"global::System.Func<{siblingType}> next", "Bind", "next");
        EmitForwardingPair(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "Bind", $"global::System.Func<global::System.Threading.Tasks.Task<{siblingType}>> next", "BindAsync", "next", awaitCall: true);
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "Then", $"global::System.Func<{siblingType}> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "Then", $"global::System.Func<global::System.Threading.Tasks.Task<{siblingType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "AndThen", $"global::System.Func<{siblingType}> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "AndThen", $"global::System.Func<global::System.Threading.Tasks.Task<{siblingType}>> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "SelectMany", $"global::System.Func<{siblingType}> next", "Bind");
        EmitForwardingAlias(sb, $"global::System.Threading.Tasks.Task<{siblingType}>", "SelectMany", $"global::System.Func<global::System.Threading.Tasks.Task<{siblingType}>> next", "Bind");
    }

    private static void EmitForwardingPair(
        IndentedStringBuilder sb,
        string returnType,
        string methodName,
        string parameters,
        string targetMethod,
        string arguments,
        bool awaitCall = false)
    {
        sb.AppendLine($"public async {returnType} {methodName}({parameters})");
        using (sb.Block())
        {
            EmitNullChecks(sb, parameters);
            sb.AppendLine("var result = await source.ConfigureAwait(false);");
            var call = $"result.{targetMethod}({arguments})";
            sb.AppendLine(awaitCall
                ? $"return await {call}.ConfigureAwait(false);"
                : $"return {call};");
        }
    }

    private static void EmitForwardingAlias(
        IndentedStringBuilder sb,
        string returnType,
        string methodName,
        string parameters,
        string targetMethod)
    {
        var argumentNames = ExtractArgumentNames(parameters);
        sb.AppendLine($"public {returnType} {methodName}({parameters}) => source.{targetMethod}({argumentNames});");
    }

    private static void EmitNullChecks(IndentedStringBuilder sb, string parameters)
    {
        sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(source);");
        foreach (var parameterName in ExtractArgumentNames(parameters).Split(new[] { ", " }, StringSplitOptions.RemoveEmptyEntries))
        {
            if (parameterName != "error")
            {
                sb.AppendLine($"global::System.ArgumentNullException.ThrowIfNull({parameterName});");
            }
        }
    }

    private static string ExtractArgumentNames(string parameters)
    {
        return string.Join(", ", SplitParameters(parameters)
            .Select(static parameter =>
            {
                var trimmed = parameter.Trim();
                var space = trimmed.LastIndexOf(' ');
                return space < 0 ? trimmed : trimmed.Substring(space + 1);
            }));
    }

    private static string[] SplitParameters(string parameters)
    {
        var parts = new System.Collections.Generic.List<string>();
        var current = new StringBuilder();
        var angleDepth = 0;

        foreach (var ch in parameters)
        {
            switch (ch)
            {
                case '<':
                    angleDepth++;
                    current.Append(ch);
                    break;
                case '>':
                    angleDepth--;
                    current.Append(ch);
                    break;
                case ',' when angleDepth == 0:
                    parts.Add(current.ToString());
                    current.Clear();
                    break;
                default:
                    current.Append(ch);
                    break;
            }
        }

        if (current.Length > 0)
        {
            parts.Add(current.ToString());
        }

        return parts.ToArray();
    }
}
