using System.Collections.Generic;
using FuncyTown.Generators.Internal;
using FuncyTown.Generators.Models;

namespace FuncyTown.Generators.Emitters;

internal static class ErrorUnionEmitter
{
    public static string Emit(ErrorUnionModel model)
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();

        var containingTypeDeclarations = SplitContainingTypeDeclarations(model);
        if (string.IsNullOrEmpty(model.Namespace))
        {
            EmitContainingTypes(sb, model, containingTypeDeclarations, index: 0);
            return sb.ToString();
        }

        sb.AppendLine($"namespace {model.Namespace}");
        using (sb.Block())
        {
            EmitContainingTypes(sb, model, containingTypeDeclarations, index: 0);
        }

        return sb.ToString();
    }

    private static string[] SplitContainingTypeDeclarations(ErrorUnionModel model)
    {
        return string.IsNullOrEmpty(model.ContainingTypeDeclarations)
            ? []
            : model.ContainingTypeDeclarations.Split('\n');
    }

    private static void EmitContainingTypes(
        IndentedStringBuilder sb,
        ErrorUnionModel model,
        string[] containingTypeDeclarations,
        int index)
    {
        if (index == containingTypeDeclarations.Length)
        {
            EmitUnionBody(sb, model);
            return;
        }

        sb.AppendLine(containingTypeDeclarations[index]);
        using (sb.Block())
        {
            EmitContainingTypes(sb, model, containingTypeDeclarations, index + 1);
        }
    }

    private static void EmitUnionBody(IndentedStringBuilder sb, ErrorUnionModel model)
    {
        var handlers = BuildHandlers(model);
        EmitJsonPolymorphismAttributes(sb, handlers);
        sb.AppendLine($"{model.Accessibility} partial class {model.TypeName} : global::FuncyTown.ICombinableError<{model.FullyQualifiedName}>");
        using (sb.Block())
        {
            sb.AppendLine($"protected {model.TypeName}() {{ }}");
            sb.AppendLine();
            sb.AppendLine("public virtual global::System.String Code => GetType().Name;");
            sb.AppendLine("public virtual global::System.String Message => GetType().Name;");
            sb.AppendLine();

            EmitExhaustiveMatch(sb, model, handlers);
            sb.AppendLine();
            EmitFallbackMatch(sb, model, handlers);
            sb.AppendLine();
            EmitExhaustiveSwitch(sb, model, handlers);
            sb.AppendLine();
            EmitFallbackSwitch(sb, model, handlers);
            sb.AppendLine();
            EmitMany(sb, model);
            sb.AppendLine();
            sb.AppendLine($"public static {model.FullyQualifiedName} Combine(global::System.Collections.Generic.IReadOnlyList<{model.FullyQualifiedName}> errors) => new Many(errors);");
        }
    }

    private static void EmitJsonPolymorphismAttributes(IndentedStringBuilder sb, Handler[] handlers)
    {
        sb.AppendLine("[global::System.Text.Json.Serialization.JsonPolymorphic(TypeDiscriminatorPropertyName = \"$case\")]");
        foreach (var handler in handlers)
        {
            sb.AppendLine($"[global::System.Text.Json.Serialization.JsonDerivedType(typeof({handler.FullyQualifiedName}), \"{handler.SimpleName}\")]");
        }
    }

    private static void EmitExhaustiveMatch(IndentedStringBuilder sb, ErrorUnionModel model, Handler[] handlers)
    {
        sb.AppendLine($"public TResult Match<TResult>({BuildHandlerParameters(handlers, nullable: false, action: false)})");
        using (sb.Block())
        {
            foreach (var handler in handlers)
            {
                sb.AppendLine($"global::System.ArgumentNullException.ThrowIfNull({handler.ParameterName});");
            }

            sb.AppendLine();

            EmitMatchCaseChecks(sb, handlers, useFallback: false);
            EmitUnhandledThrow(sb, model);
        }
    }

    private static void EmitFallbackMatch(IndentedStringBuilder sb, ErrorUnionModel model, Handler[] handlers)
    {
        var parameters = BuildHandlerParameters(handlers, nullable: true, action: false);
        if (parameters.Length > 0)
        {
            parameters += ", ";
        }

        parameters += $"global::System.Func<{model.FullyQualifiedName}, TResult> fallback";

        sb.AppendLine($"public TResult Match<TResult>({parameters})");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(fallback);");
            sb.AppendLine();
            EmitMatchCaseChecks(sb, handlers, useFallback: true);
            sb.AppendLine("return fallback(this);");
        }
    }

    private static void EmitExhaustiveSwitch(IndentedStringBuilder sb, ErrorUnionModel model, Handler[] handlers)
    {
        sb.AppendLine($"public void Switch({BuildHandlerParameters(handlers, nullable: false, action: true)})");
        using (sb.Block())
        {
            foreach (var handler in handlers)
            {
                sb.AppendLine($"global::System.ArgumentNullException.ThrowIfNull({handler.ParameterName});");
            }

            sb.AppendLine();

            EmitSwitchCaseChecks(sb, handlers, useFallback: false);
            EmitUnhandledThrow(sb, model);
        }
    }

    private static void EmitFallbackSwitch(IndentedStringBuilder sb, ErrorUnionModel model, Handler[] handlers)
    {
        var parameters = BuildHandlerParameters(handlers, nullable: true, action: true);
        if (parameters.Length > 0)
        {
            parameters += ", ";
        }

        parameters += $"global::System.Action<{model.FullyQualifiedName}> fallback";

        sb.AppendLine($"public void Switch({parameters})");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(fallback);");
            sb.AppendLine();
            EmitSwitchCaseChecks(sb, handlers, useFallback: true);
            sb.AppendLine("fallback(this);");
        }
    }

    private static string BuildHandlerParameters(Handler[] handlers, bool nullable, bool action)
    {
        var delegateName = action ? "Action" : "Func";
        var nullableSuffix = nullable ? "?" : string.Empty;
        var builder = new System.Text.StringBuilder();

        for (var i = 0; i < handlers.Length; i++)
        {
            if (i > 0)
            {
                builder.Append(", ");
            }

            var handler = handlers[i];
            if (action)
            {
                builder.Append($"global::System.{delegateName}<{handler.FullyQualifiedName}>{nullableSuffix} {handler.ParameterName}");
            }
            else
            {
                builder.Append($"global::System.{delegateName}<{handler.FullyQualifiedName}, TResult>{nullableSuffix} {handler.ParameterName}");
            }
        }

        return builder.ToString();
    }

    private static void EmitMatchCaseChecks(IndentedStringBuilder sb, Handler[] handlers, bool useFallback)
    {
        foreach (var handler in handlers)
        {
            var valueName = handler.ValueName;
            sb.AppendLine($"if (this is {handler.FullyQualifiedName} {valueName})");
            using (sb.Block())
            {
                if (useFallback)
                {
                    sb.AppendLine($"return {handler.ParameterName} is null ? fallback(this) : {handler.ParameterName}({valueName});");
                }
                else
                {
                    sb.AppendLine($"return {handler.ParameterName}({valueName});");
                }
            }
        }
    }

    private static void EmitSwitchCaseChecks(IndentedStringBuilder sb, Handler[] handlers, bool useFallback)
    {
        foreach (var handler in handlers)
        {
            var valueName = handler.ValueName;
            sb.AppendLine($"if (this is {handler.FullyQualifiedName} {valueName})");
            using (sb.Block())
            {
                if (useFallback)
                {
                    sb.AppendLine($"if ({handler.ParameterName} is not null)");
                    using (sb.Block())
                    {
                        sb.AppendLine($"{handler.ParameterName}({valueName});");
                        sb.AppendLine("return;");
                    }

                    sb.AppendLine("fallback(this);");
                    sb.AppendLine("return;");
                }
                else
                {
                    sb.AppendLine($"{handler.ParameterName}({valueName});");
                    sb.AppendLine("return;");
                }
            }
        }
    }

    private static void EmitMany(IndentedStringBuilder sb, ErrorUnionModel model)
    {
        sb.AppendLine($"public sealed partial class Many : {model.FullyQualifiedName}");
        using (sb.Block())
        {
            sb.AppendLine($"public Many(global::System.Collections.Generic.IReadOnlyList<{model.FullyQualifiedName}> errors)");
            using (sb.Block())
            {
                sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(errors);");
                sb.AppendLine("Errors = errors;");
            }

            sb.AppendLine();
            sb.AppendLine($"public global::System.Collections.Generic.IReadOnlyList<{model.FullyQualifiedName}> Errors {{ get; }}");
        }
    }

    private static Handler[] BuildHandlers(ErrorUnionModel model)
    {
        var handlers = new List<Handler>(model.Cases.Length + 1);
        foreach (var @case in model.Cases)
        {
            if (CanExposeCase(model, @case))
            {
                handlers.Add(new Handler(@case.FullyQualifiedName, @case.SimpleName));
            }
        }

        handlers.Add(new Handler($"{model.FullyQualifiedName}.Many", "Many"));
        AssignParameterNames(handlers);
        return handlers.ToArray();
    }

    private static bool CanExposeCase(ErrorUnionModel model, ErrorCaseModel @case)
    {
        if (IsPubliclyAccessible(model))
        {
            return @case.Accessibility == "public";
        }

        return @case.Accessibility == "public"
            || @case.Accessibility == "internal";
    }

    private static bool IsPubliclyAccessible(ErrorUnionModel model)
    {
        if (model.Accessibility != "public")
        {
            return false;
        }

        if (string.IsNullOrEmpty(model.ContainingTypeDeclarations))
        {
            return true;
        }

        var containingTypeDeclarations = model.ContainingTypeDeclarations.Split('\n');
        foreach (var declaration in containingTypeDeclarations)
        {
            if (!declaration.StartsWith("public ", System.StringComparison.Ordinal))
            {
                return false;
            }
        }

        return true;
    }

    private static void AssignParameterNames(List<Handler> handlers)
    {
        var usedNames = new HashSet<string>(System.StringComparer.Ordinal)
        {
            "fallback",
        };

        foreach (var handler in handlers)
        {
            var baseName = ToParameterName(handler.SimpleName);
            var parameterName = baseName;
            var suffix = 1;
            while (!usedNames.Add(ToIdentifierKey(parameterName)))
            {
                parameterName = baseName + suffix.ToString(System.Globalization.CultureInfo.InvariantCulture);
                suffix++;
            }

            handler.ParameterName = parameterName;
        }

        foreach (var handler in handlers)
        {
            var baseName = ToValueName(handler.ParameterName);
            var valueName = baseName;
            var suffix = 1;
            while (!usedNames.Add(ToIdentifierKey(valueName)))
            {
                valueName = baseName + suffix.ToString(System.Globalization.CultureInfo.InvariantCulture);
                suffix++;
            }

            handler.ValueName = valueName;
        }
    }

    private static void EmitUnhandledThrow(IndentedStringBuilder sb, ErrorUnionModel model)
    {
        sb.AppendLine($"throw new global::System.InvalidOperationException(\"Unhandled {model.TypeName} case: \" + GetType().FullName);");
    }

    private static string ToParameterName(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return "caseValue";
        }

        var parameterName = char.ToLowerInvariant(name[0]) + name.Substring(1);
        return IsKeyword(parameterName) ? "@" + parameterName : parameterName;
    }

    private static string ToValueName(string parameterName)
    {
        return ToIdentifierKey(parameterName) + "Value";
    }

    private static string ToIdentifierKey(string parameterName)
    {
        return parameterName.StartsWith("@", System.StringComparison.Ordinal)
            ? parameterName.Substring(1)
            : parameterName;
    }

    private sealed class Handler
    {
        public Handler(string fullyQualifiedName, string simpleName)
        {
            FullyQualifiedName = fullyQualifiedName;
            SimpleName = simpleName;
            ParameterName = string.Empty;
            ValueName = string.Empty;
        }

        public string FullyQualifiedName { get; }

        public string SimpleName { get; }

        public string ParameterName { get; set; }

        public string ValueName { get; set; }
    }

    private static bool IsKeyword(string value)
    {
        switch (value)
        {
            case "abstract":
            case "as":
            case "base":
            case "bool":
            case "break":
            case "byte":
            case "case":
            case "catch":
            case "char":
            case "checked":
            case "class":
            case "const":
            case "continue":
            case "decimal":
            case "default":
            case "delegate":
            case "do":
            case "double":
            case "else":
            case "enum":
            case "event":
            case "explicit":
            case "extern":
            case "false":
            case "finally":
            case "fixed":
            case "float":
            case "for":
            case "foreach":
            case "goto":
            case "if":
            case "implicit":
            case "in":
            case "int":
            case "interface":
            case "internal":
            case "is":
            case "lock":
            case "long":
            case "namespace":
            case "new":
            case "null":
            case "object":
            case "operator":
            case "out":
            case "override":
            case "params":
            case "private":
            case "protected":
            case "public":
            case "readonly":
            case "ref":
            case "return":
            case "sbyte":
            case "sealed":
            case "short":
            case "sizeof":
            case "stackalloc":
            case "static":
            case "string":
            case "struct":
            case "switch":
            case "this":
            case "throw":
            case "true":
            case "try":
            case "typeof":
            case "uint":
            case "ulong":
            case "unchecked":
            case "unsafe":
            case "ushort":
            case "using":
            case "virtual":
            case "void":
            case "volatile":
            case "while":
                return true;
            default:
                return false;
        }
    }
}
