using FuncyTown.Generators.Internal;
using FuncyTown.Generators.Models;

namespace FuncyTown.Generators.Emitters;

internal static class ResultAliasEmitter
{
    public static string Emit(ResultAliasModel model, ResultAliasFamily family)
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();

        var containingTypeDeclarations = SplitContainingTypeDeclarations(model);
        if (string.IsNullOrEmpty(model.AliasNamespace))
        {
            EmitContainingTypes(sb, model, family, containingTypeDeclarations, index: 0);
            return sb.ToString();
        }

        sb.AppendLine($"namespace {model.AliasNamespace}");
        using (sb.Block())
        {
            EmitContainingTypes(sb, model, family, containingTypeDeclarations, index: 0);
        }

        return sb.ToString();
    }

    private static string[] SplitContainingTypeDeclarations(ResultAliasModel model)
    {
        return string.IsNullOrEmpty(model.ContainingTypeDeclarations)
            ? []
            : model.ContainingTypeDeclarations.Split('\n');
    }

    private static void EmitContainingTypes(
        IndentedStringBuilder sb,
        ResultAliasModel model,
        ResultAliasFamily family,
        string[] containingTypeDeclarations,
        int index)
    {
        if (index == containingTypeDeclarations.Length)
        {
            EmitTypeBody(sb, model, family);
            return;
        }

        sb.AppendLine(containingTypeDeclarations[index]);
        using (sb.Block())
        {
            EmitContainingTypes(sb, model, family, containingTypeDeclarations, index + 1);
        }
    }

    private static void EmitTypeBody(IndentedStringBuilder sb, ResultAliasModel model, ResultAliasFamily family)
    {
        var valueType = model.ValueTypeFullyQualifiedName;
        var errorType = model.ErrorTypeFullyQualifiedName;
        var alias = model.AliasName;
        var underlying = $"global::FuncyTown.Result<{valueType}, {errorType}>";
        var converter = $"{alias}JsonConverter";
        var typeDeclaration = model.IsClassKind
            ? $"{model.AliasAccessibility} partial class {alias}"
            : $"{model.AliasAccessibility} readonly partial record struct {alias}";

        if (model.JsonConverterEnabled)
        {
            sb.AppendLine($"[global::System.Text.Json.Serialization.JsonConverter(typeof({alias}.{converter}))]");
        }

        sb.AppendLine(typeDeclaration);
        using (sb.Block())
        {
            sb.AppendLine($"private readonly {underlying} _inner;");
            sb.AppendLine();
            var constructorInitializer = model.IsClassKind ? string.Empty : " : this()";
            sb.AppendLine($"private {alias}({underlying} inner){constructorInitializer} => _inner = inner;");
            sb.AppendLine();

            EmitFactoriesAndConversions(sb, model, family, alias, valueType, errorType, underlying);
            EmitAccessors(sb, model, valueType, errorType);
            EmitChainMethods(sb, model, alias, valueType, errorType);
            EmitTryMethods(sb, model, alias, valueType, errorType);
            EmitCrossAliasOverloads(sb, model, family);
            EmitTapMethods(sb, model, alias, valueType, errorType);
            EmitMatch(sb, model, valueType, errorType);
            AsyncChainEmitter.EmitAsyncMethods(sb, model);
            sb.AppendLine("public override string ToString() => _inner.ToString();");
            if (model.JsonConverterEnabled)
            {
                sb.AppendLine();
                EmitJsonConverter(sb, model, alias, underlying, converter);
            }
        }
    }

    private static void EmitJsonConverter(
        IndentedStringBuilder sb,
        ResultAliasModel model,
        string alias,
        string underlying,
        string converter)
    {
        sb.AppendLine($"private sealed class {converter} : global::System.Text.Json.Serialization.JsonConverter<{alias}>");
        using (sb.Block())
        {
            sb.AppendLine($"public override {alias} Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)");
            using (sb.Block())
            {
                sb.AppendLine($"var result = global::System.Text.Json.JsonSerializer.Deserialize<{underlying}>(ref reader, options);");
                sb.AppendLine("if (result.IsSuccess)");
                using (sb.Block())
                {
                    if (model.IsVoidSuccess)
                    {
                        sb.AppendLine($"return {alias}.Success();");
                    }
                    else
                    {
                        sb.AppendLine($"return {alias}.Success(result.Value);");
                    }
                }

                sb.AppendLine();
                sb.AppendLine("if (result.IsFailure)");
                using (sb.Block())
                {
                    sb.AppendLine($"return {alias}.Failure(result.Error);");
                }

                sb.AppendLine();
                sb.AppendLine("throw new global::System.Text.Json.JsonException(\"Cannot deserialize an uninitialized Result alias.\");");
            }

            sb.AppendLine();
            sb.AppendLine($"public override void Write(global::System.Text.Json.Utf8JsonWriter writer, {alias} value, global::System.Text.Json.JsonSerializerOptions options)");
            using (sb.Block())
            {
                sb.AppendLine("if (!value.IsSuccess && !value.IsFailure)");
                using (sb.Block())
                {
                    sb.AppendLine("throw new global::System.Text.Json.JsonException(\"Cannot serialize an uninitialized Result alias.\");");
                }

                sb.AppendLine();
                if (model.IsVoidSuccess)
                {
                    sb.AppendLine($"var result = value.IsSuccess ? {underlying}.Success(global::FuncyTown.Unit.Value) : {underlying}.Failure(value.Error);");
                }
                else
                {
                    sb.AppendLine($"var result = value.IsSuccess ? {underlying}.Success(value.Value) : {underlying}.Failure(value.Error);");
                }

                sb.AppendLine("global::System.Text.Json.JsonSerializer.Serialize(writer, result, options);");
            }
        }
    }

    private static void EmitCrossAliasOverloads(
        IndentedStringBuilder sb,
        ResultAliasModel model,
        ResultAliasFamily family)
    {
        foreach (var sibling in family.Members)
        {
            if (!CrossAliasOverloadEmitter.CanEmit(model, sibling))
            {
                continue;
            }

            CrossAliasOverloadEmitter.Emit(sb, model, sibling);
            sb.AppendLine();
        }
    }

    private static void EmitFactoriesAndConversions(
        IndentedStringBuilder sb,
        ResultAliasModel model,
        ResultAliasFamily family,
        string alias,
        string valueType,
        string errorType,
        string underlying)
    {
        if (model.IsVoidSuccess)
        {
            sb.AppendLine($"public static {alias} Success() => new({underlying}.Success(global::FuncyTown.Unit.Value));");
        }
        else
        {
            sb.AppendLine($"public static {alias} Success({valueType} value) => new({underlying}.Success(value));");
        }

        sb.AppendLine($"public static {alias} Failure({errorType} error) => new({underlying}.Failure(error));");
        EmitCaseFailureFactories(sb, model, family, alias, errorType, underlying);
        sb.AppendLine();

        if (!model.ImplicitConversionsEnabled)
        {
            return;
        }

        if (!model.IsVoidSuccess)
        {
            sb.AppendLine($"public static implicit operator {alias}({valueType} value) => Success(value);");
        }

        sb.AppendLine($"public static implicit operator {alias}({errorType} error) => Failure(error);");
        EmitCaseImplicitConversions(sb, model, family, alias, errorType);
        sb.AppendLine();
    }

    private static void EmitCaseFailureFactories(
        IndentedStringBuilder sb,
        ResultAliasModel model,
        ResultAliasFamily family,
        string alias,
        string errorType,
        string underlying)
    {
        if (family.ErrorUnion is null)
        {
            return;
        }

        foreach (var @case in family.ErrorUnion.Cases)
        {
            if (@case.FullyQualifiedName == errorType || !CanExposeCase(model, @case))
            {
                continue;
            }

            sb.AppendLine($"public static {alias} Failure({@case.FullyQualifiedName} error) => new({underlying}.Failure(error));");
        }
    }

    private static void EmitCaseImplicitConversions(
        IndentedStringBuilder sb,
        ResultAliasModel model,
        ResultAliasFamily family,
        string alias,
        string errorType)
    {
        if (family.ErrorUnion is null)
        {
            return;
        }

        foreach (var @case in family.ErrorUnion.Cases)
        {
            if (@case.FullyQualifiedName == errorType || !CanExposeCase(model, @case))
            {
                continue;
            }

            sb.AppendLine($"public static implicit operator {alias}({@case.FullyQualifiedName} error) => Failure(error);");
        }
    }

    private static bool CanExposeCase(ResultAliasModel model, ErrorCaseModel @case)
    {
        if (IsPubliclyVisible(model))
        {
            return @case.Accessibility == "public";
        }

        return @case.Accessibility == "public"
            || @case.Accessibility == "internal";
    }

    private static bool IsPubliclyVisible(ResultAliasModel model)
    {
        if (model.AliasAccessibility != "public")
        {
            return false;
        }

        if (string.IsNullOrEmpty(model.ContainingTypeDeclarations))
        {
            return true;
        }

        var containingTypeDeclarations = model.ContainingTypeDeclarations.Split('\n');
        foreach (var declaration in containingTypeDeclarations)
        {
            if (!declaration.StartsWith("public ", System.StringComparison.Ordinal))
            {
                return false;
            }
        }

        return true;
    }

    private static void EmitAccessors(
        IndentedStringBuilder sb,
        ResultAliasModel model,
        string valueType,
        string errorType)
    {
        sb.AppendLine("public bool IsSuccess => _inner.IsSuccess;");
        sb.AppendLine("public bool IsFailure => _inner.IsFailure;");
        if (!model.IsVoidSuccess)
        {
            sb.AppendLine($"public {valueType} Value => _inner.Value;");
        }

        sb.AppendLine($"public {errorType} Error => _inner.Error;");
        sb.AppendLine();

        if (model.IsVoidSuccess)
        {
            sb.AppendLine($"public void Deconstruct(out bool isSuccess, out {errorType}? error)");
            using (sb.Block())
            {
                sb.AppendLine("isSuccess = _inner.IsSuccess;");
                sb.AppendLine("error = _inner.IsFailure ? _inner.Error : default;");
            }
        }
        else
        {
            sb.AppendLine($"public void Deconstruct(out bool isSuccess, out {valueType}? value, out {errorType}? error)");
            using (sb.Block())
            {
                sb.AppendLine("isSuccess = _inner.IsSuccess;");
                sb.AppendLine("value = _inner.IsSuccess ? _inner.Value : default;");
                sb.AppendLine("error = _inner.IsFailure ? _inner.Error : default;");
            }
        }

        sb.AppendLine();
    }

    private static void EmitTryMethods(
        IndentedStringBuilder sb,
        ResultAliasModel model,
        string alias,
        string valueType,
        string errorType)
    {
        if (!model.ErrorTypeSupportsExceptions)
        {
            return;
        }

        if (model.IsVoidSuccess)
        {
            EmitVoidTryMethods(sb, alias, errorType);
        }
        else
        {
            EmitValueTryMethods(sb, alias, valueType, errorType);
        }

        sb.AppendLine();
    }

    private static void EmitValueTryMethods(IndentedStringBuilder sb, string alias, string valueType, string errorType)
    {
        sb.AppendLine($"public {alias} MapTry(global::System.Func<{valueType}, {valueType}> selector, string? code = null, string? message = null) => new(global::FuncyTown.ResultTryExtensions.MapTry(_inner, selector, code, message));");
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> MapTry<TNew>(global::System.Func<{valueType}, TNew> selector, string? code = null, string? message = null) => global::FuncyTown.ResultTryExtensions.MapTry(_inner, selector, code, message);");
        sb.AppendLine($"public async global::System.Threading.Tasks.Task<{alias}> MapTryAsync(global::System.Func<{valueType}, global::System.Threading.Tasks.Task<{valueType}>> selector, string? code = null, string? message = null)");
        using (sb.Block())
        {
            sb.AppendLine("return new(await global::FuncyTown.ResultTryExtensions.MapTryAsync(_inner, selector, code, message).ConfigureAwait(false));");
        }

        sb.AppendLine($"public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>> MapTryAsync<TNew>(global::System.Func<{valueType}, global::System.Threading.Tasks.Task<TNew>> selector, string? code = null, string? message = null) => global::FuncyTown.ResultTryExtensions.MapTryAsync(_inner, selector, code, message);");
        sb.AppendLine();

        sb.AppendLine($"public {alias} ThenTry(global::System.Func<{valueType}, {alias}> next, string? code = null, string? message = null)");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(next);");
            sb.AppendLine($"return new(global::FuncyTown.ResultTryExtensions.ThenTry(_inner, value => next(value)._inner, code, message));");
        }

        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> ThenTry<TNew>(global::System.Func<{valueType}, global::FuncyTown.Result<TNew, {errorType}>> next, string? code = null, string? message = null) => global::FuncyTown.ResultTryExtensions.ThenTry(_inner, next, code, message);");
        sb.AppendLine($"public async global::System.Threading.Tasks.Task<{alias}> ThenTryAsync(global::System.Func<{valueType}, global::System.Threading.Tasks.Task<{alias}>> next, string? code = null, string? message = null)");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(next);");
            sb.AppendLine($"return new(await global::FuncyTown.ResultTryExtensions.ThenTryAsync(_inner, async value => (await next(value).ConfigureAwait(false))._inner, code, message).ConfigureAwait(false));");
        }

        sb.AppendLine($"public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>> ThenTryAsync<TNew>(global::System.Func<{valueType}, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>> next, string? code = null, string? message = null) => global::FuncyTown.ResultTryExtensions.ThenTryAsync(_inner, next, code, message);");
    }

    private static void EmitVoidTryMethods(IndentedStringBuilder sb, string alias, string errorType)
    {
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> MapTry<TNew>(global::System.Func<TNew> selector, string? code = null, string? message = null)");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(selector);");
            sb.AppendLine("return global::FuncyTown.ResultTryExtensions.MapTry(_inner, _ => selector(), code, message);");
        }

        sb.AppendLine($"public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>> MapTryAsync<TNew>(global::System.Func<global::System.Threading.Tasks.Task<TNew>> selector, string? code = null, string? message = null)");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(selector);");
            sb.AppendLine("return global::FuncyTown.ResultTryExtensions.MapTryAsync(_inner, _ => selector(), code, message);");
        }

        sb.AppendLine();
        sb.AppendLine($"public {alias} ThenTry(global::System.Func<{alias}> next, string? code = null, string? message = null)");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(next);");
            sb.AppendLine($"return new(global::FuncyTown.ResultTryExtensions.ThenTry(_inner, _ => next()._inner, code, message));");
        }

        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> ThenTry<TNew>(global::System.Func<global::FuncyTown.Result<TNew, {errorType}>> next, string? code = null, string? message = null)");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(next);");
            sb.AppendLine("return global::FuncyTown.ResultTryExtensions.ThenTry(_inner, _ => next(), code, message);");
        }

        sb.AppendLine($"public async global::System.Threading.Tasks.Task<{alias}> ThenTryAsync(global::System.Func<global::System.Threading.Tasks.Task<{alias}>> next, string? code = null, string? message = null)");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(next);");
            sb.AppendLine($"return new(await global::FuncyTown.ResultTryExtensions.ThenTryAsync(_inner, async _ => (await next().ConfigureAwait(false))._inner, code, message).ConfigureAwait(false));");
        }

        sb.AppendLine($"public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>> ThenTryAsync<TNew>(global::System.Func<global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, {errorType}>>> next, string? code = null, string? message = null)");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(next);");
            sb.AppendLine("return global::FuncyTown.ResultTryExtensions.ThenTryAsync(_inner, _ => next(), code, message);");
        }
    }

    private static void EmitChainMethods(
        IndentedStringBuilder sb,
        ResultAliasModel model,
        string alias,
        string valueType,
        string errorType)
    {
        if (model.IsVoidSuccess)
        {
            EmitVoidChainMethods(sb, alias, errorType);
        }
        else
        {
            EmitValueChainMethods(sb, alias, valueType, errorType);
        }

        sb.AppendLine();
    }

    private static void EmitValueChainMethods(IndentedStringBuilder sb, string alias, string valueType, string errorType)
    {
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> Map<TNew>(global::System.Func<{valueType}, TNew> selector) => _inner.Map(selector);");
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> Transform<TNew>(global::System.Func<{valueType}, TNew> selector) => Map(selector);");
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> Select<TNew>(global::System.Func<{valueType}, TNew> selector) => Map(selector);");
        sb.AppendLine();

        sb.AppendLine($"public {alias} Bind(global::System.Func<{valueType}, {alias}> next)");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(next);");
            sb.AppendLine($"return _inner.IsSuccess ? next(_inner.Value) : Failure(_inner.Error);");
        }

        sb.AppendLine($"public {alias} Then(global::System.Func<{valueType}, {alias}> next) => Bind(next);");
        sb.AppendLine($"public {alias} AndThen(global::System.Func<{valueType}, {alias}> next) => Bind(next);");
        sb.AppendLine($"public {alias} SelectMany(global::System.Func<{valueType}, {alias}> next) => Bind(next);");
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> Bind<TNew>(global::System.Func<{valueType}, global::FuncyTown.Result<TNew, {errorType}>> next) => _inner.Bind(next);");
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> Then<TNew>(global::System.Func<{valueType}, global::FuncyTown.Result<TNew, {errorType}>> next) => _inner.Bind(next);");
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> AndThen<TNew>(global::System.Func<{valueType}, global::FuncyTown.Result<TNew, {errorType}>> next) => _inner.Bind(next);");
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> SelectMany<TNew>(global::System.Func<{valueType}, global::FuncyTown.Result<TNew, {errorType}>> next) => _inner.Bind(next);");
        sb.AppendLine();

        sb.AppendLine($"public global::FuncyTown.Result<{valueType}, TNewError> MapError<TNewError>(global::System.Func<{errorType}, TNewError> selector) => _inner.MapError(selector);");
        sb.AppendLine($"public global::FuncyTown.Result<{valueType}, TNewError> TransformError<TNewError>(global::System.Func<{errorType}, TNewError> selector) => MapError(selector);");
        sb.AppendLine($"public {alias} MapError(global::System.Func<{errorType}, {errorType}> selector) => new(_inner.MapError(selector));");
        sb.AppendLine($"public {alias} TransformError(global::System.Func<{errorType}, {errorType}> selector) => MapError(selector);");
        sb.AppendLine();

        sb.AppendLine($"public {alias} Recover(global::System.Func<{errorType}, {valueType}> fallback) => new(_inner.Recover(fallback));");
        sb.AppendLine($"public {alias} OrElse(global::System.Func<{errorType}, {valueType}> fallback) => Recover(fallback);");
        sb.AppendLine($"public {alias} RecoverWith(global::System.Func<{errorType}, {alias}> fallback)");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(fallback);");
            sb.AppendLine("return _inner.IsSuccess ? this : fallback(_inner.Error);");
        }

        sb.AppendLine($"public {alias} OrElseThen(global::System.Func<{errorType}, {alias}> fallback) => RecoverWith(fallback);");
        sb.AppendLine($"public {alias} Ensure(global::System.Func<{valueType}, bool> predicate, {errorType} error) => new(_inner.Ensure(predicate, error));");
        sb.AppendLine($"public {alias} Validate(global::System.Func<{valueType}, bool> predicate, {errorType} error) => Ensure(predicate, error);");
    }

    private static void EmitVoidChainMethods(IndentedStringBuilder sb, string alias, string errorType)
    {
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> Map<TNew>(global::System.Func<TNew> selector) => _inner.Map(_ => selector());");
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> Transform<TNew>(global::System.Func<TNew> selector) => Map(selector);");
        sb.AppendLine();

        sb.AppendLine($"public {alias} Bind(global::System.Func<{alias}> next)");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(next);");
            sb.AppendLine($"return _inner.IsSuccess ? next() : Failure(_inner.Error);");
        }

        sb.AppendLine($"public {alias} Then(global::System.Func<{alias}> next) => Bind(next);");
        sb.AppendLine($"public {alias} AndThen(global::System.Func<{alias}> next) => Bind(next);");
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> Bind<TNew>(global::System.Func<global::FuncyTown.Result<TNew, {errorType}>> next) => _inner.Bind(_ => next());");
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> Then<TNew>(global::System.Func<global::FuncyTown.Result<TNew, {errorType}>> next) => _inner.Bind(_ => next());");
        sb.AppendLine($"public global::FuncyTown.Result<TNew, {errorType}> AndThen<TNew>(global::System.Func<global::FuncyTown.Result<TNew, {errorType}>> next) => _inner.Bind(_ => next());");
        sb.AppendLine();

        sb.AppendLine($"public global::FuncyTown.Result<global::FuncyTown.Unit, TNewError> MapError<TNewError>(global::System.Func<{errorType}, TNewError> selector) => _inner.MapError(selector);");
        sb.AppendLine($"public global::FuncyTown.Result<global::FuncyTown.Unit, TNewError> TransformError<TNewError>(global::System.Func<{errorType}, TNewError> selector) => MapError(selector);");
        sb.AppendLine($"public {alias} MapError(global::System.Func<{errorType}, {errorType}> selector) => new(_inner.MapError(selector));");
        sb.AppendLine($"public {alias} TransformError(global::System.Func<{errorType}, {errorType}> selector) => MapError(selector);");
        sb.AppendLine();

        sb.AppendLine($"public {alias} RecoverWith(global::System.Func<{errorType}, {alias}> fallback)");
        using (sb.Block())
        {
            sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(fallback);");
            sb.AppendLine("return _inner.IsSuccess ? this : fallback(_inner.Error);");
        }

        sb.AppendLine($"public {alias} OrElseThen(global::System.Func<{errorType}, {alias}> fallback) => RecoverWith(fallback);");
    }

    private static void EmitTapMethods(
        IndentedStringBuilder sb,
        ResultAliasModel model,
        string alias,
        string valueType,
        string errorType)
    {
        if (model.IsVoidSuccess)
        {
            sb.AppendLine($"public {alias} OnSuccess(global::System.Action action)");
            using (sb.Block())
            {
                sb.AppendLine("global::System.ArgumentNullException.ThrowIfNull(action);");
                sb.AppendLine("return new(_inner.OnSuccess(_ => action()));");
            }

            sb.AppendLine($"public {alias} IfSuccessful(global::System.Action action) => OnSuccess(action);");
            sb.AppendLine($"public {alias} Tap(global::System.Action action) => OnSuccess(action);");
        }
        else
        {
            sb.AppendLine($"public {alias} OnSuccess(global::System.Action<{valueType}> action) => new(_inner.OnSuccess(action));");
            sb.AppendLine($"public {alias} IfSuccessful(global::System.Action<{valueType}> action) => OnSuccess(action);");
            sb.AppendLine($"public {alias} Tap(global::System.Action<{valueType}> action) => OnSuccess(action);");
        }

        sb.AppendLine($"public {alias} OnFailure(global::System.Action<{errorType}> action) => new(_inner.OnFailure(action));");
        sb.AppendLine($"public {alias} IfFailed(global::System.Action<{errorType}> action) => OnFailure(action);");
        sb.AppendLine($"public {alias} TapError(global::System.Action<{errorType}> action) => OnFailure(action);");
        sb.AppendLine();
    }

    private static void EmitMatch(
        IndentedStringBuilder sb,
        ResultAliasModel model,
        string valueType,
        string errorType)
    {
        if (model.IsVoidSuccess)
        {
            sb.AppendLine($"public TResult Match<TResult>(global::System.Func<TResult> onSuccess, global::System.Func<{errorType}, TResult> onFailure) => _inner.Match(_ => onSuccess(), onFailure);");
        }
        else
        {
            sb.AppendLine($"public TResult Match<TResult>(global::System.Func<{valueType}, TResult> onSuccess, global::System.Func<{errorType}, TResult> onFailure) => _inner.Match(onSuccess, onFailure);");
        }
    }
}
