//HintName: MyApp_StringResult.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591

namespace MyApp
{
    [global::System.Text.Json.Serialization.JsonConverter(typeof(StringResult.StringResultJsonConverter))]
    public readonly partial record struct StringResult
    {
        private readonly global::FuncyTown.Result<string, global::MyApp.FakeError> _inner;
        
        private StringResult(global::FuncyTown.Result<string, global::MyApp.FakeError> inner) => _inner = inner;
        
        public static StringResult Success(string value) => new(global::FuncyTown.Result<string, global::MyApp.FakeError>.Success(value));
        public static StringResult Failure(global::MyApp.FakeError error) => new(global::FuncyTown.Result<string, global::MyApp.FakeError>.Failure(error));
        
        public static implicit operator StringResult(string value) => Success(value);
        public static implicit operator StringResult(global::MyApp.FakeError error) => Failure(error);
        
        public bool IsSuccess => _inner.IsSuccess;
        public bool IsFailure => _inner.IsFailure;
        public string Value => _inner.Value;
        public global::MyApp.FakeError Error => _inner.Error;
        
        public void Deconstruct(out bool isSuccess, out string? value, out global::MyApp.FakeError? error)
        {
            isSuccess = _inner.IsSuccess;
            value = _inner.IsSuccess ? _inner.Value : default;
            error = _inner.IsFailure ? _inner.Error : default;
        }
        
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Map<TNew>(global::System.Func<string, TNew> selector) => _inner.Map(selector);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Transform<TNew>(global::System.Func<string, TNew> selector) => Map(selector);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Select<TNew>(global::System.Func<string, TNew> selector) => Map(selector);
        
        public StringResult Bind(global::System.Func<string, StringResult> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            return _inner.IsSuccess ? next(_inner.Value) : Failure(_inner.Error);
        }
        public StringResult Then(global::System.Func<string, StringResult> next) => Bind(next);
        public StringResult AndThen(global::System.Func<string, StringResult> next) => Bind(next);
        public StringResult SelectMany(global::System.Func<string, StringResult> next) => Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Bind<TNew>(global::System.Func<string, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Then<TNew>(global::System.Func<string, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> AndThen<TNew>(global::System.Func<string, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> SelectMany<TNew>(global::System.Func<string, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(next);
        
        public global::FuncyTown.Result<string, TNewError> MapError<TNewError>(global::System.Func<global::MyApp.FakeError, TNewError> selector) => _inner.MapError(selector);
        public global::FuncyTown.Result<string, TNewError> TransformError<TNewError>(global::System.Func<global::MyApp.FakeError, TNewError> selector) => MapError(selector);
        public StringResult MapError(global::System.Func<global::MyApp.FakeError, global::MyApp.FakeError> selector) => new(_inner.MapError(selector));
        public StringResult TransformError(global::System.Func<global::MyApp.FakeError, global::MyApp.FakeError> selector) => MapError(selector);
        
        public StringResult Recover(global::System.Func<global::MyApp.FakeError, string> fallback) => new(_inner.Recover(fallback));
        public StringResult OrElse(global::System.Func<global::MyApp.FakeError, string> fallback) => Recover(fallback);
        public StringResult RecoverWith(global::System.Func<global::MyApp.FakeError, StringResult> fallback)
        {
            global::System.ArgumentNullException.ThrowIfNull(fallback);
            return _inner.IsSuccess ? this : fallback(_inner.Error);
        }
        public StringResult OrElseThen(global::System.Func<global::MyApp.FakeError, StringResult> fallback) => RecoverWith(fallback);
        public StringResult Ensure(global::System.Func<string, bool> predicate, global::MyApp.FakeError error) => new(_inner.Ensure(predicate, error));
        public StringResult Validate(global::System.Func<string, bool> predicate, global::MyApp.FakeError error) => Ensure(predicate, error);
        
        public global::MyApp.IntResult Bind(global::System.Func<string, global::MyApp.IntResult> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            if (_inner.IsSuccess)
            {
                return next(_inner.Value);
            }
            if (_inner.IsFailure)
            {
                return global::MyApp.IntResult.Failure(_inner.Error);
            }
            throw new global::FuncyTown.ResultException("Cannot Bind an uninitialized Result.");
        }
        public global::MyApp.IntResult Then(global::System.Func<string, global::MyApp.IntResult> next) => Bind(next);
        public global::MyApp.IntResult AndThen(global::System.Func<string, global::MyApp.IntResult> next) => Bind(next);
        public global::MyApp.IntResult SelectMany(global::System.Func<string, global::MyApp.IntResult> next) => Bind(next);
        public async global::System.Threading.Tasks.Task<global::MyApp.IntResult> BindAsync(global::System.Func<string, global::System.Threading.Tasks.Task<global::MyApp.IntResult>> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            if (_inner.IsSuccess)
            {
                return await next(_inner.Value).ConfigureAwait(false);
            }
            if (_inner.IsFailure)
            {
                return global::MyApp.IntResult.Failure(_inner.Error);
            }
            throw new global::FuncyTown.ResultException("Cannot BindAsync an uninitialized Result.");
        }
        public global::System.Threading.Tasks.Task<global::MyApp.IntResult> ThenAsync(global::System.Func<string, global::System.Threading.Tasks.Task<global::MyApp.IntResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<global::MyApp.IntResult> AndThenAsync(global::System.Func<string, global::System.Threading.Tasks.Task<global::MyApp.IntResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<global::MyApp.IntResult> SelectManyAsync(global::System.Func<string, global::System.Threading.Tasks.Task<global::MyApp.IntResult>> next) => BindAsync(next);
        
        public StringResult OnSuccess(global::System.Action<string> action) => new(_inner.OnSuccess(action));
        public StringResult IfSuccessful(global::System.Action<string> action) => OnSuccess(action);
        public StringResult Tap(global::System.Action<string> action) => OnSuccess(action);
        public StringResult OnFailure(global::System.Action<global::MyApp.FakeError> action) => new(_inner.OnFailure(action));
        public StringResult IfFailed(global::System.Action<global::MyApp.FakeError> action) => OnFailure(action);
        public StringResult TapError(global::System.Action<global::MyApp.FakeError> action) => OnFailure(action);
        
        public TResult Match<TResult>(global::System.Func<string, TResult> onSuccess, global::System.Func<global::MyApp.FakeError, TResult> onFailure) => _inner.Match(onSuccess, onFailure);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> MapAsync<TNew>(global::System.Func<string, global::System.Threading.Tasks.Task<TNew>> selector) => _inner.MapAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> TransformAsync<TNew>(global::System.Func<string, global::System.Threading.Tasks.Task<TNew>> selector) => MapAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> SelectAsync<TNew>(global::System.Func<string, global::System.Threading.Tasks.Task<TNew>> selector) => MapAsync(selector);
        public async global::System.Threading.Tasks.Task<StringResult> BindAsync(global::System.Func<string, global::System.Threading.Tasks.Task<StringResult>> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            if (_inner.IsSuccess)
            {
                return await next(_inner.Value).ConfigureAwait(false);
            }
            if (_inner.IsFailure)
            {
                return Failure(_inner.Error);
            }
            throw new global::FuncyTown.ResultException("Cannot BindAsync an uninitialized Result.");
        }
        public global::System.Threading.Tasks.Task<StringResult> ThenAsync(global::System.Func<string, global::System.Threading.Tasks.Task<StringResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<StringResult> AndThenAsync(global::System.Func<string, global::System.Threading.Tasks.Task<StringResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<StringResult> SelectManyAsync(global::System.Func<string, global::System.Threading.Tasks.Task<StringResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> BindAsync<TNew>(global::System.Func<string, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> ThenAsync<TNew>(global::System.Func<string, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> AndThenAsync<TNew>(global::System.Func<string, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> SelectManyAsync<TNew>(global::System.Func<string, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<string, TNewError>> MapErrorAsync<TNewError>(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TNewError>> selector) => _inner.MapErrorAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<string, TNewError>> TransformErrorAsync<TNewError>(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TNewError>> selector) => MapErrorAsync(selector);
        public async global::System.Threading.Tasks.Task<StringResult> MapErrorAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.FakeError>> selector)
        {
            return new(await _inner.MapErrorAsync(selector).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<StringResult> TransformErrorAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.FakeError>> selector) => MapErrorAsync(selector);
        public async global::System.Threading.Tasks.Task<StringResult> RecoverAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<string>> fallback)
        {
            return new(await _inner.RecoverAsync(fallback).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<StringResult> OrElseAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<string>> fallback) => RecoverAsync(fallback);
        public async global::System.Threading.Tasks.Task<StringResult> RecoverWithAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<StringResult>> fallback)
        {
            global::System.ArgumentNullException.ThrowIfNull(fallback);
            if (_inner.IsSuccess)
            {
                return this;
            }
            if (_inner.IsFailure)
            {
                return await fallback(_inner.Error).ConfigureAwait(false);
            }
            throw new global::FuncyTown.ResultException("Cannot RecoverWithAsync on an uninitialized Result.");
        }
        public global::System.Threading.Tasks.Task<StringResult> OrElseThenAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<StringResult>> fallback) => RecoverWithAsync(fallback);
        public async global::System.Threading.Tasks.Task<StringResult> EnsureAsync(global::System.Func<string, global::System.Threading.Tasks.Task<bool>> predicate, global::MyApp.FakeError error)
        {
            return new(await _inner.EnsureAsync(predicate, error).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<StringResult> ValidateAsync(global::System.Func<string, global::System.Threading.Tasks.Task<bool>> predicate, global::MyApp.FakeError error) => EnsureAsync(predicate, error);
        public async global::System.Threading.Tasks.Task<StringResult> OnSuccessAsync(global::System.Func<string, global::System.Threading.Tasks.Task> action)
        {
            return new(await _inner.OnSuccessAsync(action).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<StringResult> IfSuccessfulAsync(global::System.Func<string, global::System.Threading.Tasks.Task> action) => OnSuccessAsync(action);
        public global::System.Threading.Tasks.Task<StringResult> TapAsync(global::System.Func<string, global::System.Threading.Tasks.Task> action) => OnSuccessAsync(action);
        public async global::System.Threading.Tasks.Task<StringResult> OnFailureAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action)
        {
            return new(await _inner.OnFailureAsync(action).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<StringResult> IfFailedAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action) => OnFailureAsync(action);
        public global::System.Threading.Tasks.Task<StringResult> TapErrorAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action) => OnFailureAsync(action);
        public global::System.Threading.Tasks.Task<TResult> MatchAsync<TResult>(global::System.Func<string, global::System.Threading.Tasks.Task<TResult>> onSuccess, global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TResult>> onFailure) => _inner.MatchAsync(onSuccess, onFailure);
        public override string ToString() => _inner.ToString();
        
        private sealed class StringResultJsonConverter : global::System.Text.Json.Serialization.JsonConverter<StringResult>
        {
            public override StringResult Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
            {
                var result = global::System.Text.Json.JsonSerializer.Deserialize<global::FuncyTown.Result<string, global::MyApp.FakeError>>(ref reader, options);
                if (result.IsSuccess)
                {
                    return StringResult.Success(result.Value);
                }
                
                if (result.IsFailure)
                {
                    return StringResult.Failure(result.Error);
                }
                
                throw new global::System.Text.Json.JsonException("Cannot deserialize an uninitialized Result alias.");
            }
            
            public override void Write(global::System.Text.Json.Utf8JsonWriter writer, StringResult value, global::System.Text.Json.JsonSerializerOptions options)
            {
                if (!value.IsSuccess && !value.IsFailure)
                {
                    throw new global::System.Text.Json.JsonException("Cannot serialize an uninitialized Result alias.");
                }
                
                var result = value.IsSuccess ? global::FuncyTown.Result<string, global::MyApp.FakeError>.Success(value.Value) : global::FuncyTown.Result<string, global::MyApp.FakeError>.Failure(value.Error);
                global::System.Text.Json.JsonSerializer.Serialize(writer, result, options);
            }
        }
    }
}
