//HintName: MyApp_UserError.Union.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591

namespace MyApp
{
    [global::System.Text.Json.Serialization.JsonPolymorphic(TypeDiscriminatorPropertyName = "$case")]
    [global::System.Text.Json.Serialization.JsonDerivedType(typeof(global::MyApp.NotFound), "NotFound")]
    [global::System.Text.Json.Serialization.JsonDerivedType(typeof(global::MyApp.Invalid), "Invalid")]
    [global::System.Text.Json.Serialization.JsonDerivedType(typeof(global::MyApp.UserError.Many), "Many")]
    public partial class UserError : global::FuncyTown.ICombinableError<global::MyApp.UserError>
    {
        protected UserError() { }
        
        public virtual global::System.String Code => GetType().Name;
        public virtual global::System.String Message => GetType().Name;
        
        public TResult Match<TResult>(global::System.Func<global::MyApp.NotFound, TResult> notFound, global::System.Func<global::MyApp.Invalid, TResult> invalid, global::System.Func<global::MyApp.UserError.Many, TResult> many)
        {
            global::System.ArgumentNullException.ThrowIfNull(notFound);
            global::System.ArgumentNullException.ThrowIfNull(invalid);
            global::System.ArgumentNullException.ThrowIfNull(many);
            
            if (this is global::MyApp.NotFound notFoundValue)
            {
                return notFound(notFoundValue);
            }
            if (this is global::MyApp.Invalid invalidValue)
            {
                return invalid(invalidValue);
            }
            if (this is global::MyApp.UserError.Many manyValue)
            {
                return many(manyValue);
            }
            throw new global::System.InvalidOperationException("Unhandled UserError case: " + GetType().FullName);
        }
        
        public TResult Match<TResult>(global::System.Func<global::MyApp.NotFound, TResult>? notFound, global::System.Func<global::MyApp.Invalid, TResult>? invalid, global::System.Func<global::MyApp.UserError.Many, TResult>? many, global::System.Func<global::MyApp.UserError, TResult> fallback)
        {
            global::System.ArgumentNullException.ThrowIfNull(fallback);
            
            if (this is global::MyApp.NotFound notFoundValue)
            {
                return notFound is null ? fallback(this) : notFound(notFoundValue);
            }
            if (this is global::MyApp.Invalid invalidValue)
            {
                return invalid is null ? fallback(this) : invalid(invalidValue);
            }
            if (this is global::MyApp.UserError.Many manyValue)
            {
                return many is null ? fallback(this) : many(manyValue);
            }
            return fallback(this);
        }
        
        public void Switch(global::System.Action<global::MyApp.NotFound> notFound, global::System.Action<global::MyApp.Invalid> invalid, global::System.Action<global::MyApp.UserError.Many> many)
        {
            global::System.ArgumentNullException.ThrowIfNull(notFound);
            global::System.ArgumentNullException.ThrowIfNull(invalid);
            global::System.ArgumentNullException.ThrowIfNull(many);
            
            if (this is global::MyApp.NotFound notFoundValue)
            {
                notFound(notFoundValue);
                return;
            }
            if (this is global::MyApp.Invalid invalidValue)
            {
                invalid(invalidValue);
                return;
            }
            if (this is global::MyApp.UserError.Many manyValue)
            {
                many(manyValue);
                return;
            }
            throw new global::System.InvalidOperationException("Unhandled UserError case: " + GetType().FullName);
        }
        
        public void Switch(global::System.Action<global::MyApp.NotFound>? notFound, global::System.Action<global::MyApp.Invalid>? invalid, global::System.Action<global::MyApp.UserError.Many>? many, global::System.Action<global::MyApp.UserError> fallback)
        {
            global::System.ArgumentNullException.ThrowIfNull(fallback);
            
            if (this is global::MyApp.NotFound notFoundValue)
            {
                if (notFound is not null)
                {
                    notFound(notFoundValue);
                    return;
                }
                fallback(this);
                return;
            }
            if (this is global::MyApp.Invalid invalidValue)
            {
                if (invalid is not null)
                {
                    invalid(invalidValue);
                    return;
                }
                fallback(this);
                return;
            }
            if (this is global::MyApp.UserError.Many manyValue)
            {
                if (many is not null)
                {
                    many(manyValue);
                    return;
                }
                fallback(this);
                return;
            }
            fallback(this);
        }
        
        public sealed partial class Many : global::MyApp.UserError
        {
            public Many(global::System.Collections.Generic.IReadOnlyList<global::MyApp.UserError> errors)
            {
                global::System.ArgumentNullException.ThrowIfNull(errors);
                Errors = errors;
            }
            
            public global::System.Collections.Generic.IReadOnlyList<global::MyApp.UserError> Errors { get; }
        }
        
        public static global::MyApp.UserError Combine(global::System.Collections.Generic.IReadOnlyList<global::MyApp.UserError> errors) => new Many(errors);
    }
}
