//HintName: MyApp_IntResult.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591

namespace MyApp
{
    [global::System.Text.Json.Serialization.JsonConverter(typeof(IntResult.IntResultJsonConverter))]
    public readonly partial record struct IntResult
    {
        private readonly global::FuncyTown.Result<int, global::MyApp.FakeError> _inner;
        
        private IntResult(global::FuncyTown.Result<int, global::MyApp.FakeError> inner) : this() => _inner = inner;
        
        public static IntResult Success(int value) => new(global::FuncyTown.Result<int, global::MyApp.FakeError>.Success(value));
        public static IntResult Failure(global::MyApp.FakeError error) => new(global::FuncyTown.Result<int, global::MyApp.FakeError>.Failure(error));
        
        public static implicit operator IntResult(int value) => Success(value);
        public static implicit operator IntResult(global::MyApp.FakeError error) => Failure(error);
        
        public bool IsSuccess => _inner.IsSuccess;
        public bool IsFailure => _inner.IsFailure;
        public int Value => _inner.Value;
        public global::MyApp.FakeError Error => _inner.Error;
        
        public void Deconstruct(out bool isSuccess, out int? value, out global::MyApp.FakeError? error)
        {
            isSuccess = _inner.IsSuccess;
            value = _inner.IsSuccess ? _inner.Value : default;
            error = _inner.IsFailure ? _inner.Error : default;
        }
        
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Map<TNew>(global::System.Func<int, TNew> selector) => _inner.Map(selector);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Transform<TNew>(global::System.Func<int, TNew> selector) => Map(selector);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Select<TNew>(global::System.Func<int, TNew> selector) => Map(selector);
        
        public IntResult Bind(global::System.Func<int, IntResult> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            return _inner.IsSuccess ? next(_inner.Value) : Failure(_inner.Error);
        }
        public IntResult Then(global::System.Func<int, IntResult> next) => Bind(next);
        public IntResult AndThen(global::System.Func<int, IntResult> next) => Bind(next);
        public IntResult SelectMany(global::System.Func<int, IntResult> next) => Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Bind<TNew>(global::System.Func<int, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Then<TNew>(global::System.Func<int, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> AndThen<TNew>(global::System.Func<int, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> SelectMany<TNew>(global::System.Func<int, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(next);
        
        public global::FuncyTown.Result<int, TNewError> MapError<TNewError>(global::System.Func<global::MyApp.FakeError, TNewError> selector) => _inner.MapError(selector);
        public global::FuncyTown.Result<int, TNewError> TransformError<TNewError>(global::System.Func<global::MyApp.FakeError, TNewError> selector) => MapError(selector);
        public IntResult MapError(global::System.Func<global::MyApp.FakeError, global::MyApp.FakeError> selector) => new(_inner.MapError(selector));
        public IntResult TransformError(global::System.Func<global::MyApp.FakeError, global::MyApp.FakeError> selector) => MapError(selector);
        
        public IntResult Recover(global::System.Func<global::MyApp.FakeError, int> fallback) => new(_inner.Recover(fallback));
        public IntResult OrElse(global::System.Func<global::MyApp.FakeError, int> fallback) => Recover(fallback);
        public IntResult RecoverWith(global::System.Func<global::MyApp.FakeError, IntResult> fallback)
        {
            global::System.ArgumentNullException.ThrowIfNull(fallback);
            return _inner.IsSuccess ? this : fallback(_inner.Error);
        }
        public IntResult OrElseThen(global::System.Func<global::MyApp.FakeError, IntResult> fallback) => RecoverWith(fallback);
        public IntResult Ensure(global::System.Func<int, bool> predicate, global::MyApp.FakeError error) => new(_inner.Ensure(predicate, error));
        public IntResult Validate(global::System.Func<int, bool> predicate, global::MyApp.FakeError error) => Ensure(predicate, error);
        
        public IntResult OnSuccess(global::System.Action<int> action) => new(_inner.OnSuccess(action));
        public IntResult IfSuccessful(global::System.Action<int> action) => OnSuccess(action);
        public IntResult Tap(global::System.Action<int> action) => OnSuccess(action);
        public IntResult OnFailure(global::System.Action<global::MyApp.FakeError> action) => new(_inner.OnFailure(action));
        public IntResult IfFailed(global::System.Action<global::MyApp.FakeError> action) => OnFailure(action);
        public IntResult TapError(global::System.Action<global::MyApp.FakeError> action) => OnFailure(action);
        
        public TResult Match<TResult>(global::System.Func<int, TResult> onSuccess, global::System.Func<global::MyApp.FakeError, TResult> onFailure) => _inner.Match(onSuccess, onFailure);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> MapAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<TNew>> selector) => _inner.MapAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> TransformAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<TNew>> selector) => MapAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> SelectAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<TNew>> selector) => MapAsync(selector);
        public async global::System.Threading.Tasks.Task<IntResult> BindAsync(global::System.Func<int, global::System.Threading.Tasks.Task<IntResult>> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            if (_inner.IsSuccess)
            {
                return await next(_inner.Value).ConfigureAwait(false);
            }
            if (_inner.IsFailure)
            {
                return Failure(_inner.Error);
            }
            throw new global::FuncyTown.ResultException("Cannot BindAsync an uninitialized Result.");
        }
        public global::System.Threading.Tasks.Task<IntResult> ThenAsync(global::System.Func<int, global::System.Threading.Tasks.Task<IntResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<IntResult> AndThenAsync(global::System.Func<int, global::System.Threading.Tasks.Task<IntResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<IntResult> SelectManyAsync(global::System.Func<int, global::System.Threading.Tasks.Task<IntResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> BindAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> ThenAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> AndThenAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> SelectManyAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<int, TNewError>> MapErrorAsync<TNewError>(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TNewError>> selector) => _inner.MapErrorAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<int, TNewError>> TransformErrorAsync<TNewError>(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TNewError>> selector) => MapErrorAsync(selector);
        public async global::System.Threading.Tasks.Task<IntResult> MapErrorAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.FakeError>> selector)
        {
            return new(await _inner.MapErrorAsync(selector).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<IntResult> TransformErrorAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.FakeError>> selector) => MapErrorAsync(selector);
        public async global::System.Threading.Tasks.Task<IntResult> RecoverAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<int>> fallback)
        {
            return new(await _inner.RecoverAsync(fallback).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<IntResult> OrElseAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<int>> fallback) => RecoverAsync(fallback);
        public async global::System.Threading.Tasks.Task<IntResult> RecoverWithAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<IntResult>> fallback)
        {
            global::System.ArgumentNullException.ThrowIfNull(fallback);
            if (_inner.IsSuccess)
            {
                return this;
            }
            if (_inner.IsFailure)
            {
                return await fallback(_inner.Error).ConfigureAwait(false);
            }
            throw new global::FuncyTown.ResultException("Cannot RecoverWithAsync on an uninitialized Result.");
        }
        public global::System.Threading.Tasks.Task<IntResult> OrElseThenAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<IntResult>> fallback) => RecoverWithAsync(fallback);
        public async global::System.Threading.Tasks.Task<IntResult> EnsureAsync(global::System.Func<int, global::System.Threading.Tasks.Task<bool>> predicate, global::MyApp.FakeError error)
        {
            return new(await _inner.EnsureAsync(predicate, error).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<IntResult> ValidateAsync(global::System.Func<int, global::System.Threading.Tasks.Task<bool>> predicate, global::MyApp.FakeError error) => EnsureAsync(predicate, error);
        public async global::System.Threading.Tasks.Task<IntResult> OnSuccessAsync(global::System.Func<int, global::System.Threading.Tasks.Task> action)
        {
            return new(await _inner.OnSuccessAsync(action).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<IntResult> IfSuccessfulAsync(global::System.Func<int, global::System.Threading.Tasks.Task> action) => OnSuccessAsync(action);
        public global::System.Threading.Tasks.Task<IntResult> TapAsync(global::System.Func<int, global::System.Threading.Tasks.Task> action) => OnSuccessAsync(action);
        public async global::System.Threading.Tasks.Task<IntResult> OnFailureAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action)
        {
            return new(await _inner.OnFailureAsync(action).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<IntResult> IfFailedAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action) => OnFailureAsync(action);
        public global::System.Threading.Tasks.Task<IntResult> TapErrorAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action) => OnFailureAsync(action);
        public global::System.Threading.Tasks.Task<TResult> MatchAsync<TResult>(global::System.Func<int, global::System.Threading.Tasks.Task<TResult>> onSuccess, global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TResult>> onFailure) => _inner.MatchAsync(onSuccess, onFailure);
        public override string ToString() => _inner.ToString();
        
        private sealed class IntResultJsonConverter : global::System.Text.Json.Serialization.JsonConverter<IntResult>
        {
            public override IntResult Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
            {
                var result = global::System.Text.Json.JsonSerializer.Deserialize<global::FuncyTown.Result<int, global::MyApp.FakeError>>(ref reader, options);
                if (result.IsSuccess)
                {
                    return IntResult.Success(result.Value);
                }
                
                if (result.IsFailure)
                {
                    return IntResult.Failure(result.Error);
                }
                
                throw new global::System.Text.Json.JsonException("Cannot deserialize an uninitialized Result alias.");
            }
            
            public override void Write(global::System.Text.Json.Utf8JsonWriter writer, IntResult value, global::System.Text.Json.JsonSerializerOptions options)
            {
                if (!value.IsSuccess && !value.IsFailure)
                {
                    throw new global::System.Text.Json.JsonException("Cannot serialize an uninitialized Result alias.");
                }
                
                var result = value.IsSuccess ? global::FuncyTown.Result<int, global::MyApp.FakeError>.Success(value.Value) : global::FuncyTown.Result<int, global::MyApp.FakeError>.Failure(value.Error);
                global::System.Text.Json.JsonSerializer.Serialize(writer, result, options);
            }
        }
    }
}
