//HintName: MyApp_UserResult.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591

namespace MyApp
{
    [global::System.Text.Json.Serialization.JsonConverter(typeof(UserResult.UserResultJsonConverter))]
    public readonly partial record struct UserResult
    {
        private readonly global::FuncyTown.Result<global::MyApp.User, global::MyApp.UserError> _inner;
        
        private UserResult(global::FuncyTown.Result<global::MyApp.User, global::MyApp.UserError> inner) : this() => _inner = inner;
        
        public static UserResult Success(global::MyApp.User value) => new(global::FuncyTown.Result<global::MyApp.User, global::MyApp.UserError>.Success(value));
        public static UserResult Failure(global::MyApp.UserError error) => new(global::FuncyTown.Result<global::MyApp.User, global::MyApp.UserError>.Failure(error));
        public static UserResult Failure(global::MyApp.NotFound error) => new(global::FuncyTown.Result<global::MyApp.User, global::MyApp.UserError>.Failure(error));
        public static UserResult Failure(global::MyApp.Invalid error) => new(global::FuncyTown.Result<global::MyApp.User, global::MyApp.UserError>.Failure(error));
        
        public static implicit operator UserResult(global::MyApp.User value) => Success(value);
        public static implicit operator UserResult(global::MyApp.UserError error) => Failure(error);
        public static implicit operator UserResult(global::MyApp.NotFound error) => Failure(error);
        public static implicit operator UserResult(global::MyApp.Invalid error) => Failure(error);
        
        public bool IsSuccess => _inner.IsSuccess;
        public bool IsFailure => _inner.IsFailure;
        public global::MyApp.User Value => _inner.Value;
        public global::MyApp.UserError Error => _inner.Error;
        
        public void Deconstruct(out bool isSuccess, out global::MyApp.User? value, out global::MyApp.UserError? error)
        {
            isSuccess = _inner.IsSuccess;
            value = _inner.IsSuccess ? _inner.Value : default;
            error = _inner.IsFailure ? _inner.Error : default;
        }
        
        public global::FuncyTown.Result<TNew, global::MyApp.UserError> Map<TNew>(global::System.Func<global::MyApp.User, TNew> selector) => _inner.Map(selector);
        public global::FuncyTown.Result<TNew, global::MyApp.UserError> Transform<TNew>(global::System.Func<global::MyApp.User, TNew> selector) => Map(selector);
        public global::FuncyTown.Result<TNew, global::MyApp.UserError> Select<TNew>(global::System.Func<global::MyApp.User, TNew> selector) => Map(selector);
        
        public UserResult Bind(global::System.Func<global::MyApp.User, UserResult> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            return _inner.IsSuccess ? next(_inner.Value) : Failure(_inner.Error);
        }
        public UserResult Then(global::System.Func<global::MyApp.User, UserResult> next) => Bind(next);
        public UserResult AndThen(global::System.Func<global::MyApp.User, UserResult> next) => Bind(next);
        public UserResult SelectMany(global::System.Func<global::MyApp.User, UserResult> next) => Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.UserError> Bind<TNew>(global::System.Func<global::MyApp.User, global::FuncyTown.Result<TNew, global::MyApp.UserError>> next) => _inner.Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.UserError> Then<TNew>(global::System.Func<global::MyApp.User, global::FuncyTown.Result<TNew, global::MyApp.UserError>> next) => _inner.Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.UserError> AndThen<TNew>(global::System.Func<global::MyApp.User, global::FuncyTown.Result<TNew, global::MyApp.UserError>> next) => _inner.Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.UserError> SelectMany<TNew>(global::System.Func<global::MyApp.User, global::FuncyTown.Result<TNew, global::MyApp.UserError>> next) => _inner.Bind(next);
        
        public global::FuncyTown.Result<global::MyApp.User, TNewError> MapError<TNewError>(global::System.Func<global::MyApp.UserError, TNewError> selector) => _inner.MapError(selector);
        public global::FuncyTown.Result<global::MyApp.User, TNewError> TransformError<TNewError>(global::System.Func<global::MyApp.UserError, TNewError> selector) => MapError(selector);
        public UserResult MapError(global::System.Func<global::MyApp.UserError, global::MyApp.UserError> selector) => new(_inner.MapError(selector));
        public UserResult TransformError(global::System.Func<global::MyApp.UserError, global::MyApp.UserError> selector) => MapError(selector);
        
        public UserResult Recover(global::System.Func<global::MyApp.UserError, global::MyApp.User> fallback) => new(_inner.Recover(fallback));
        public UserResult OrElse(global::System.Func<global::MyApp.UserError, global::MyApp.User> fallback) => Recover(fallback);
        public UserResult RecoverWith(global::System.Func<global::MyApp.UserError, UserResult> fallback)
        {
            global::System.ArgumentNullException.ThrowIfNull(fallback);
            return _inner.IsSuccess ? this : fallback(_inner.Error);
        }
        public UserResult OrElseThen(global::System.Func<global::MyApp.UserError, UserResult> fallback) => RecoverWith(fallback);
        public UserResult Ensure(global::System.Func<global::MyApp.User, bool> predicate, global::MyApp.UserError error) => new(_inner.Ensure(predicate, error));
        public UserResult Validate(global::System.Func<global::MyApp.User, bool> predicate, global::MyApp.UserError error) => Ensure(predicate, error);
        
        public UserResult OnSuccess(global::System.Action<global::MyApp.User> action) => new(_inner.OnSuccess(action));
        public UserResult IfSuccessful(global::System.Action<global::MyApp.User> action) => OnSuccess(action);
        public UserResult Tap(global::System.Action<global::MyApp.User> action) => OnSuccess(action);
        public UserResult OnFailure(global::System.Action<global::MyApp.UserError> action) => new(_inner.OnFailure(action));
        public UserResult IfFailed(global::System.Action<global::MyApp.UserError> action) => OnFailure(action);
        public UserResult TapError(global::System.Action<global::MyApp.UserError> action) => OnFailure(action);
        
        public TResult Match<TResult>(global::System.Func<global::MyApp.User, TResult> onSuccess, global::System.Func<global::MyApp.UserError, TResult> onFailure) => _inner.Match(onSuccess, onFailure);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> MapAsync<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<TNew>> selector) => _inner.MapAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> TransformAsync<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<TNew>> selector) => MapAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> SelectAsync<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<TNew>> selector) => MapAsync(selector);
        public async global::System.Threading.Tasks.Task<UserResult> BindAsync(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<UserResult>> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            if (_inner.IsSuccess)
            {
                return await next(_inner.Value).ConfigureAwait(false);
            }
            if (_inner.IsFailure)
            {
                return Failure(_inner.Error);
            }
            throw new global::FuncyTown.ResultException("Cannot BindAsync an uninitialized Result.");
        }
        public global::System.Threading.Tasks.Task<UserResult> ThenAsync(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<UserResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<UserResult> AndThenAsync(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<UserResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<UserResult> SelectManyAsync(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<UserResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> BindAsync<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> ThenAsync<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> AndThenAsync<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> SelectManyAsync<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::MyApp.User, TNewError>> MapErrorAsync<TNewError>(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<TNewError>> selector) => _inner.MapErrorAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::MyApp.User, TNewError>> TransformErrorAsync<TNewError>(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<TNewError>> selector) => MapErrorAsync(selector);
        public async global::System.Threading.Tasks.Task<UserResult> MapErrorAsync(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<global::MyApp.UserError>> selector)
        {
            return new(await _inner.MapErrorAsync(selector).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<UserResult> TransformErrorAsync(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<global::MyApp.UserError>> selector) => MapErrorAsync(selector);
        public async global::System.Threading.Tasks.Task<UserResult> RecoverAsync(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<global::MyApp.User>> fallback)
        {
            return new(await _inner.RecoverAsync(fallback).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<UserResult> OrElseAsync(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<global::MyApp.User>> fallback) => RecoverAsync(fallback);
        public async global::System.Threading.Tasks.Task<UserResult> RecoverWithAsync(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<UserResult>> fallback)
        {
            global::System.ArgumentNullException.ThrowIfNull(fallback);
            if (_inner.IsSuccess)
            {
                return this;
            }
            if (_inner.IsFailure)
            {
                return await fallback(_inner.Error).ConfigureAwait(false);
            }
            throw new global::FuncyTown.ResultException("Cannot RecoverWithAsync on an uninitialized Result.");
        }
        public global::System.Threading.Tasks.Task<UserResult> OrElseThenAsync(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<UserResult>> fallback) => RecoverWithAsync(fallback);
        public async global::System.Threading.Tasks.Task<UserResult> EnsureAsync(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<bool>> predicate, global::MyApp.UserError error)
        {
            return new(await _inner.EnsureAsync(predicate, error).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<UserResult> ValidateAsync(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<bool>> predicate, global::MyApp.UserError error) => EnsureAsync(predicate, error);
        public async global::System.Threading.Tasks.Task<UserResult> OnSuccessAsync(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task> action)
        {
            return new(await _inner.OnSuccessAsync(action).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<UserResult> IfSuccessfulAsync(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task> action) => OnSuccessAsync(action);
        public global::System.Threading.Tasks.Task<UserResult> TapAsync(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task> action) => OnSuccessAsync(action);
        public async global::System.Threading.Tasks.Task<UserResult> OnFailureAsync(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task> action)
        {
            return new(await _inner.OnFailureAsync(action).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<UserResult> IfFailedAsync(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task> action) => OnFailureAsync(action);
        public global::System.Threading.Tasks.Task<UserResult> TapErrorAsync(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task> action) => OnFailureAsync(action);
        public global::System.Threading.Tasks.Task<TResult> MatchAsync<TResult>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<TResult>> onSuccess, global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<TResult>> onFailure) => _inner.MatchAsync(onSuccess, onFailure);
        public override string ToString() => _inner.ToString();
        
        private sealed class UserResultJsonConverter : global::System.Text.Json.Serialization.JsonConverter<UserResult>
        {
            public override UserResult Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
            {
                var result = global::System.Text.Json.JsonSerializer.Deserialize<global::FuncyTown.Result<global::MyApp.User, global::MyApp.UserError>>(ref reader, options);
                if (result.IsSuccess)
                {
                    return UserResult.Success(result.Value);
                }
                
                if (result.IsFailure)
                {
                    return UserResult.Failure(result.Error);
                }
                
                throw new global::System.Text.Json.JsonException("Cannot deserialize an uninitialized Result alias.");
            }
            
            public override void Write(global::System.Text.Json.Utf8JsonWriter writer, UserResult value, global::System.Text.Json.JsonSerializerOptions options)
            {
                if (!value.IsSuccess && !value.IsFailure)
                {
                    throw new global::System.Text.Json.JsonException("Cannot serialize an uninitialized Result alias.");
                }
                
                var result = value.IsSuccess ? global::FuncyTown.Result<global::MyApp.User, global::MyApp.UserError>.Success(value.Value) : global::FuncyTown.Result<global::MyApp.User, global::MyApp.UserError>.Failure(value.Error);
                global::System.Text.Json.JsonSerializer.Serialize(writer, result, options);
            }
        }
    }
}
