//HintName: MyApp_UserResult.TaskExtensions.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591, CA1034

namespace MyApp
{
    public static class UserResultTaskExtensions
    {
        extension(global::System.Threading.Tasks.Task<global::MyApp.UserResult> source)
        {
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> Map<TNew>(global::System.Func<global::MyApp.User, TNew> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return result.Map(selector);
            }
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> Map<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<TNew>> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return await result.MapAsync(selector).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> Transform<TNew>(global::System.Func<global::MyApp.User, TNew> selector) => source.Map(selector);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> Transform<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<TNew>> selector) => source.Map(selector);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> Select<TNew>(global::System.Func<global::MyApp.User, TNew> selector) => source.Map(selector);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> Select<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<TNew>> selector) => source.Map(selector);
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> Bind(global::System.Func<global::MyApp.User, global::MyApp.UserResult> next)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(next);
                var result = await source.ConfigureAwait(false);
                return result.Bind(next);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> Bind(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<global::MyApp.UserResult>> next)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(next);
                var result = await source.ConfigureAwait(false);
                return await result.BindAsync(next).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> Then(global::System.Func<global::MyApp.User, global::MyApp.UserResult> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> Then(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<global::MyApp.UserResult>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> AndThen(global::System.Func<global::MyApp.User, global::MyApp.UserResult> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> AndThen(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<global::MyApp.UserResult>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> SelectMany(global::System.Func<global::MyApp.User, global::MyApp.UserResult> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> SelectMany(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<global::MyApp.UserResult>> next) => source.Bind(next);
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> Bind<TNew>(global::System.Func<global::MyApp.User, global::FuncyTown.Result<TNew, global::MyApp.UserError>> next)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(next);
                var result = await source.ConfigureAwait(false);
                return result.Bind(next);
            }
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> Bind<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>>> next)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(next);
                var result = await source.ConfigureAwait(false);
                return await result.BindAsync(next).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> Then<TNew>(global::System.Func<global::MyApp.User, global::FuncyTown.Result<TNew, global::MyApp.UserError>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> Then<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> AndThen<TNew>(global::System.Func<global::MyApp.User, global::FuncyTown.Result<TNew, global::MyApp.UserError>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> AndThen<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> SelectMany<TNew>(global::System.Func<global::MyApp.User, global::FuncyTown.Result<TNew, global::MyApp.UserError>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>> SelectMany<TNew>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.UserError>>> next) => source.Bind(next);
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::MyApp.User, TNewError>> MapError<TNewError>(global::System.Func<global::MyApp.UserError, TNewError> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return result.MapError(selector);
            }
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::MyApp.User, TNewError>> MapError<TNewError>(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<TNewError>> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return await result.MapErrorAsync(selector).ConfigureAwait(false);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> MapError(global::System.Func<global::MyApp.UserError, global::MyApp.UserError> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return result.MapError(selector);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> MapError(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<global::MyApp.UserError>> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return await result.MapErrorAsync(selector).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::MyApp.User, TNewError>> TransformError<TNewError>(global::System.Func<global::MyApp.UserError, TNewError> selector) => source.MapError(selector);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::MyApp.User, TNewError>> TransformError<TNewError>(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<TNewError>> selector) => source.MapError(selector);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> TransformError(global::System.Func<global::MyApp.UserError, global::MyApp.UserError> selector) => source.MapError(selector);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> TransformError(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<global::MyApp.UserError>> selector) => source.MapError(selector);
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> Recover(global::System.Func<global::MyApp.UserError, global::MyApp.User> fallback)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(fallback);
                var result = await source.ConfigureAwait(false);
                return result.Recover(fallback);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> Recover(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<global::MyApp.User>> fallback)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(fallback);
                var result = await source.ConfigureAwait(false);
                return await result.RecoverAsync(fallback).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> OrElse(global::System.Func<global::MyApp.UserError, global::MyApp.User> fallback) => source.Recover(fallback);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> OrElse(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<global::MyApp.User>> fallback) => source.Recover(fallback);
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> RecoverWith(global::System.Func<global::MyApp.UserError, global::MyApp.UserResult> fallback)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(fallback);
                var result = await source.ConfigureAwait(false);
                return result.RecoverWith(fallback);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> RecoverWith(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<global::MyApp.UserResult>> fallback)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(fallback);
                var result = await source.ConfigureAwait(false);
                return await result.RecoverWithAsync(fallback).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> OrElseThen(global::System.Func<global::MyApp.UserError, global::MyApp.UserResult> fallback) => source.RecoverWith(fallback);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> OrElseThen(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<global::MyApp.UserResult>> fallback) => source.RecoverWith(fallback);
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> OnSuccess(global::System.Action<global::MyApp.User> action)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(action);
                var result = await source.ConfigureAwait(false);
                return result.OnSuccess(action);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> OnSuccess(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task> action)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(action);
                var result = await source.ConfigureAwait(false);
                return await result.OnSuccessAsync(action).ConfigureAwait(false);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> OnFailure(global::System.Action<global::MyApp.UserError> action)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(action);
                var result = await source.ConfigureAwait(false);
                return result.OnFailure(action);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> OnFailure(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task> action)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(action);
                var result = await source.ConfigureAwait(false);
                return await result.OnFailureAsync(action).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> IfSuccessful(global::System.Action<global::MyApp.User> action) => source.OnSuccess(action);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> IfSuccessful(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task> action) => source.OnSuccess(action);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> Tap(global::System.Action<global::MyApp.User> action) => source.OnSuccess(action);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> Tap(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task> action) => source.OnSuccess(action);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> IfFailed(global::System.Action<global::MyApp.UserError> action) => source.OnFailure(action);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> IfFailed(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task> action) => source.OnFailure(action);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> TapError(global::System.Action<global::MyApp.UserError> action) => source.OnFailure(action);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> TapError(global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task> action) => source.OnFailure(action);
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> Ensure(global::System.Func<global::MyApp.User, bool> predicate, global::MyApp.UserError error)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(predicate);
                var result = await source.ConfigureAwait(false);
                return result.Ensure(predicate, error);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.UserResult> Ensure(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<bool>> predicate, global::MyApp.UserError error)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(predicate);
                var result = await source.ConfigureAwait(false);
                return await result.EnsureAsync(predicate, error).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> Validate(global::System.Func<global::MyApp.User, bool> predicate, global::MyApp.UserError error) => source.Ensure(predicate, error);
            public global::System.Threading.Tasks.Task<global::MyApp.UserResult> Validate(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<bool>> predicate, global::MyApp.UserError error) => source.Ensure(predicate, error);
            public async global::System.Threading.Tasks.Task<TResult> Match<TResult>(global::System.Func<global::MyApp.User, TResult> onSuccess, global::System.Func<global::MyApp.UserError, TResult> onFailure)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(onSuccess);
                global::System.ArgumentNullException.ThrowIfNull(onFailure);
                var result = await source.ConfigureAwait(false);
                return result.Match(onSuccess, onFailure);
            }
            public async global::System.Threading.Tasks.Task<TResult> Match<TResult>(global::System.Func<global::MyApp.User, global::System.Threading.Tasks.Task<TResult>> onSuccess, global::System.Func<global::MyApp.UserError, global::System.Threading.Tasks.Task<TResult>> onFailure)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(onSuccess);
                global::System.ArgumentNullException.ThrowIfNull(onFailure);
                var result = await source.ConfigureAwait(false);
                return await result.MatchAsync(onSuccess, onFailure).ConfigureAwait(false);
            }
        }
    }
}
