//HintName: MyApp_VoidResult.TaskExtensions.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591, CA1034

namespace MyApp
{
    public static class VoidResultTaskExtensions
    {
        extension(global::System.Threading.Tasks.Task<global::MyApp.VoidResult> source)
        {
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Map<TNew>(global::System.Func<TNew> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return result.Map(selector);
            }
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Map<TNew>(global::System.Func<global::System.Threading.Tasks.Task<TNew>> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return await result.MapAsync(selector).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Transform<TNew>(global::System.Func<TNew> selector) => source.Map(selector);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Transform<TNew>(global::System.Func<global::System.Threading.Tasks.Task<TNew>> selector) => source.Map(selector);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Select<TNew>(global::System.Func<TNew> selector) => source.Map(selector);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Select<TNew>(global::System.Func<global::System.Threading.Tasks.Task<TNew>> selector) => source.Map(selector);
            public async global::System.Threading.Tasks.Task<global::MyApp.VoidResult> Bind(global::System.Func<global::MyApp.VoidResult> next)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(next);
                var result = await source.ConfigureAwait(false);
                return result.Bind(next);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.VoidResult> Bind(global::System.Func<global::System.Threading.Tasks.Task<global::MyApp.VoidResult>> next)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(next);
                var result = await source.ConfigureAwait(false);
                return await result.BindAsync(next).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> Then(global::System.Func<global::MyApp.VoidResult> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> Then(global::System.Func<global::System.Threading.Tasks.Task<global::MyApp.VoidResult>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> AndThen(global::System.Func<global::MyApp.VoidResult> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> AndThen(global::System.Func<global::System.Threading.Tasks.Task<global::MyApp.VoidResult>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> SelectMany(global::System.Func<global::MyApp.VoidResult> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> SelectMany(global::System.Func<global::System.Threading.Tasks.Task<global::MyApp.VoidResult>> next) => source.Bind(next);
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Bind<TNew>(global::System.Func<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(next);
                var result = await source.ConfigureAwait(false);
                return result.Bind(next);
            }
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Bind<TNew>(global::System.Func<global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(next);
                var result = await source.ConfigureAwait(false);
                return await result.BindAsync(next).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Then<TNew>(global::System.Func<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Then<TNew>(global::System.Func<global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> AndThen<TNew>(global::System.Func<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> AndThen<TNew>(global::System.Func<global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> SelectMany<TNew>(global::System.Func<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> SelectMany<TNew>(global::System.Func<global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => source.Bind(next);
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::FuncyTown.Unit, TNewError>> MapError<TNewError>(global::System.Func<global::MyApp.FakeError, TNewError> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return result.MapError(selector);
            }
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::FuncyTown.Unit, TNewError>> MapError<TNewError>(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TNewError>> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return await result.MapErrorAsync(selector).ConfigureAwait(false);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.VoidResult> MapError(global::System.Func<global::MyApp.FakeError, global::MyApp.FakeError> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return result.MapError(selector);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.VoidResult> MapError(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.FakeError>> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return await result.MapErrorAsync(selector).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::FuncyTown.Unit, TNewError>> TransformError<TNewError>(global::System.Func<global::MyApp.FakeError, TNewError> selector) => source.MapError(selector);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::FuncyTown.Unit, TNewError>> TransformError<TNewError>(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TNewError>> selector) => source.MapError(selector);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> TransformError(global::System.Func<global::MyApp.FakeError, global::MyApp.FakeError> selector) => source.MapError(selector);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> TransformError(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.FakeError>> selector) => source.MapError(selector);
            public async global::System.Threading.Tasks.Task<global::MyApp.VoidResult> RecoverWith(global::System.Func<global::MyApp.FakeError, global::MyApp.VoidResult> fallback)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(fallback);
                var result = await source.ConfigureAwait(false);
                return result.RecoverWith(fallback);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.VoidResult> RecoverWith(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.VoidResult>> fallback)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(fallback);
                var result = await source.ConfigureAwait(false);
                return await result.RecoverWithAsync(fallback).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> OrElseThen(global::System.Func<global::MyApp.FakeError, global::MyApp.VoidResult> fallback) => source.RecoverWith(fallback);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> OrElseThen(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.VoidResult>> fallback) => source.RecoverWith(fallback);
            public async global::System.Threading.Tasks.Task<global::MyApp.VoidResult> OnSuccess(global::System.Action action)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(action);
                var result = await source.ConfigureAwait(false);
                return result.OnSuccess(action);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.VoidResult> OnSuccess(global::System.Func<global::System.Threading.Tasks.Task> action)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(action);
                var result = await source.ConfigureAwait(false);
                return await result.OnSuccessAsync(action).ConfigureAwait(false);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.VoidResult> OnFailure(global::System.Action<global::MyApp.FakeError> action)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(action);
                var result = await source.ConfigureAwait(false);
                return result.OnFailure(action);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.VoidResult> OnFailure(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(action);
                var result = await source.ConfigureAwait(false);
                return await result.OnFailureAsync(action).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> IfSuccessful(global::System.Action action) => source.OnSuccess(action);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> IfSuccessful(global::System.Func<global::System.Threading.Tasks.Task> action) => source.OnSuccess(action);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> Tap(global::System.Action action) => source.OnSuccess(action);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> Tap(global::System.Func<global::System.Threading.Tasks.Task> action) => source.OnSuccess(action);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> IfFailed(global::System.Action<global::MyApp.FakeError> action) => source.OnFailure(action);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> IfFailed(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action) => source.OnFailure(action);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> TapError(global::System.Action<global::MyApp.FakeError> action) => source.OnFailure(action);
            public global::System.Threading.Tasks.Task<global::MyApp.VoidResult> TapError(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action) => source.OnFailure(action);
            public async global::System.Threading.Tasks.Task<TResult> Match<TResult>(global::System.Func<TResult> onSuccess, global::System.Func<global::MyApp.FakeError, TResult> onFailure)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(onSuccess);
                global::System.ArgumentNullException.ThrowIfNull(onFailure);
                var result = await source.ConfigureAwait(false);
                return result.Match(onSuccess, onFailure);
            }
            public async global::System.Threading.Tasks.Task<TResult> Match<TResult>(global::System.Func<global::System.Threading.Tasks.Task<TResult>> onSuccess, global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TResult>> onFailure)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(onSuccess);
                global::System.ArgumentNullException.ThrowIfNull(onFailure);
                var result = await source.ConfigureAwait(false);
                return await result.MatchAsync(onSuccess, onFailure).ConfigureAwait(false);
            }
        }
    }
}
