//HintName: MyApp_ExplicitResult.TaskExtensions.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591, CA1034

namespace MyApp
{
    public static class ExplicitResultTaskExtensions
    {
        extension(global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> source)
        {
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Map<TNew>(global::System.Func<int, TNew> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return result.Map(selector);
            }
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Map<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<TNew>> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return await result.MapAsync(selector).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Transform<TNew>(global::System.Func<int, TNew> selector) => source.Map(selector);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Transform<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<TNew>> selector) => source.Map(selector);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Select<TNew>(global::System.Func<int, TNew> selector) => source.Map(selector);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Select<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<TNew>> selector) => source.Map(selector);
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> Bind(global::System.Func<int, global::MyApp.ExplicitResult> next)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(next);
                var result = await source.ConfigureAwait(false);
                return result.Bind(next);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> Bind(global::System.Func<int, global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult>> next)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(next);
                var result = await source.ConfigureAwait(false);
                return await result.BindAsync(next).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> Then(global::System.Func<int, global::MyApp.ExplicitResult> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> Then(global::System.Func<int, global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> AndThen(global::System.Func<int, global::MyApp.ExplicitResult> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> AndThen(global::System.Func<int, global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> SelectMany(global::System.Func<int, global::MyApp.ExplicitResult> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> SelectMany(global::System.Func<int, global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult>> next) => source.Bind(next);
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Bind<TNew>(global::System.Func<int, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(next);
                var result = await source.ConfigureAwait(false);
                return result.Bind(next);
            }
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Bind<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(next);
                var result = await source.ConfigureAwait(false);
                return await result.BindAsync(next).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Then<TNew>(global::System.Func<int, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> Then<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> AndThen<TNew>(global::System.Func<int, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> AndThen<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> SelectMany<TNew>(global::System.Func<int, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => source.Bind(next);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> SelectMany<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => source.Bind(next);
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<int, TNewError>> MapError<TNewError>(global::System.Func<global::MyApp.FakeError, TNewError> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return result.MapError(selector);
            }
            public async global::System.Threading.Tasks.Task<global::FuncyTown.Result<int, TNewError>> MapError<TNewError>(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TNewError>> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return await result.MapErrorAsync(selector).ConfigureAwait(false);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> MapError(global::System.Func<global::MyApp.FakeError, global::MyApp.FakeError> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return result.MapError(selector);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> MapError(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.FakeError>> selector)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(selector);
                var result = await source.ConfigureAwait(false);
                return await result.MapErrorAsync(selector).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<int, TNewError>> TransformError<TNewError>(global::System.Func<global::MyApp.FakeError, TNewError> selector) => source.MapError(selector);
            public global::System.Threading.Tasks.Task<global::FuncyTown.Result<int, TNewError>> TransformError<TNewError>(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TNewError>> selector) => source.MapError(selector);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> TransformError(global::System.Func<global::MyApp.FakeError, global::MyApp.FakeError> selector) => source.MapError(selector);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> TransformError(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.FakeError>> selector) => source.MapError(selector);
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> Recover(global::System.Func<global::MyApp.FakeError, int> fallback)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(fallback);
                var result = await source.ConfigureAwait(false);
                return result.Recover(fallback);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> Recover(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<int>> fallback)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(fallback);
                var result = await source.ConfigureAwait(false);
                return await result.RecoverAsync(fallback).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> OrElse(global::System.Func<global::MyApp.FakeError, int> fallback) => source.Recover(fallback);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> OrElse(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<int>> fallback) => source.Recover(fallback);
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> RecoverWith(global::System.Func<global::MyApp.FakeError, global::MyApp.ExplicitResult> fallback)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(fallback);
                var result = await source.ConfigureAwait(false);
                return result.RecoverWith(fallback);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> RecoverWith(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult>> fallback)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(fallback);
                var result = await source.ConfigureAwait(false);
                return await result.RecoverWithAsync(fallback).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> OrElseThen(global::System.Func<global::MyApp.FakeError, global::MyApp.ExplicitResult> fallback) => source.RecoverWith(fallback);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> OrElseThen(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult>> fallback) => source.RecoverWith(fallback);
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> OnSuccess(global::System.Action<int> action)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(action);
                var result = await source.ConfigureAwait(false);
                return result.OnSuccess(action);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> OnSuccess(global::System.Func<int, global::System.Threading.Tasks.Task> action)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(action);
                var result = await source.ConfigureAwait(false);
                return await result.OnSuccessAsync(action).ConfigureAwait(false);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> OnFailure(global::System.Action<global::MyApp.FakeError> action)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(action);
                var result = await source.ConfigureAwait(false);
                return result.OnFailure(action);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> OnFailure(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(action);
                var result = await source.ConfigureAwait(false);
                return await result.OnFailureAsync(action).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> IfSuccessful(global::System.Action<int> action) => source.OnSuccess(action);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> IfSuccessful(global::System.Func<int, global::System.Threading.Tasks.Task> action) => source.OnSuccess(action);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> Tap(global::System.Action<int> action) => source.OnSuccess(action);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> Tap(global::System.Func<int, global::System.Threading.Tasks.Task> action) => source.OnSuccess(action);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> IfFailed(global::System.Action<global::MyApp.FakeError> action) => source.OnFailure(action);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> IfFailed(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action) => source.OnFailure(action);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> TapError(global::System.Action<global::MyApp.FakeError> action) => source.OnFailure(action);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> TapError(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action) => source.OnFailure(action);
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> Ensure(global::System.Func<int, bool> predicate, global::MyApp.FakeError error)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(predicate);
                var result = await source.ConfigureAwait(false);
                return result.Ensure(predicate, error);
            }
            public async global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> Ensure(global::System.Func<int, global::System.Threading.Tasks.Task<bool>> predicate, global::MyApp.FakeError error)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(predicate);
                var result = await source.ConfigureAwait(false);
                return await result.EnsureAsync(predicate, error).ConfigureAwait(false);
            }
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> Validate(global::System.Func<int, bool> predicate, global::MyApp.FakeError error) => source.Ensure(predicate, error);
            public global::System.Threading.Tasks.Task<global::MyApp.ExplicitResult> Validate(global::System.Func<int, global::System.Threading.Tasks.Task<bool>> predicate, global::MyApp.FakeError error) => source.Ensure(predicate, error);
            public async global::System.Threading.Tasks.Task<TResult> Match<TResult>(global::System.Func<int, TResult> onSuccess, global::System.Func<global::MyApp.FakeError, TResult> onFailure)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(onSuccess);
                global::System.ArgumentNullException.ThrowIfNull(onFailure);
                var result = await source.ConfigureAwait(false);
                return result.Match(onSuccess, onFailure);
            }
            public async global::System.Threading.Tasks.Task<TResult> Match<TResult>(global::System.Func<int, global::System.Threading.Tasks.Task<TResult>> onSuccess, global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TResult>> onFailure)
            {
                global::System.ArgumentNullException.ThrowIfNull(source);
                global::System.ArgumentNullException.ThrowIfNull(onSuccess);
                global::System.ArgumentNullException.ThrowIfNull(onFailure);
                var result = await source.ConfigureAwait(false);
                return await result.MatchAsync(onSuccess, onFailure).ConfigureAwait(false);
            }
        }
    }
}
