//HintName: MyApp_VoidResult.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591

namespace MyApp
{
    [global::System.Text.Json.Serialization.JsonConverter(typeof(VoidResult.VoidResultJsonConverter))]
    public readonly partial record struct VoidResult
    {
        private readonly global::FuncyTown.Result<global::FuncyTown.Unit, global::MyApp.FakeError> _inner;
        
        private VoidResult(global::FuncyTown.Result<global::FuncyTown.Unit, global::MyApp.FakeError> inner) : this() => _inner = inner;
        
        public static VoidResult Success() => new(global::FuncyTown.Result<global::FuncyTown.Unit, global::MyApp.FakeError>.Success(global::FuncyTown.Unit.Value));
        public static VoidResult Failure(global::MyApp.FakeError error) => new(global::FuncyTown.Result<global::FuncyTown.Unit, global::MyApp.FakeError>.Failure(error));
        
        public static implicit operator VoidResult(global::MyApp.FakeError error) => Failure(error);
        
        public bool IsSuccess => _inner.IsSuccess;
        public bool IsFailure => _inner.IsFailure;
        public global::MyApp.FakeError Error => _inner.Error;
        
        public void Deconstruct(out bool isSuccess, out global::MyApp.FakeError? error)
        {
            isSuccess = _inner.IsSuccess;
            error = _inner.IsFailure ? _inner.Error : default;
        }
        
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Map<TNew>(global::System.Func<TNew> selector) => _inner.Map(_ => selector());
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Transform<TNew>(global::System.Func<TNew> selector) => Map(selector);
        
        public VoidResult Bind(global::System.Func<VoidResult> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            return _inner.IsSuccess ? next() : Failure(_inner.Error);
        }
        public VoidResult Then(global::System.Func<VoidResult> next) => Bind(next);
        public VoidResult AndThen(global::System.Func<VoidResult> next) => Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Bind<TNew>(global::System.Func<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(_ => next());
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Then<TNew>(global::System.Func<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(_ => next());
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> AndThen<TNew>(global::System.Func<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(_ => next());
        
        public global::FuncyTown.Result<global::FuncyTown.Unit, TNewError> MapError<TNewError>(global::System.Func<global::MyApp.FakeError, TNewError> selector) => _inner.MapError(selector);
        public global::FuncyTown.Result<global::FuncyTown.Unit, TNewError> TransformError<TNewError>(global::System.Func<global::MyApp.FakeError, TNewError> selector) => MapError(selector);
        public VoidResult MapError(global::System.Func<global::MyApp.FakeError, global::MyApp.FakeError> selector) => new(_inner.MapError(selector));
        public VoidResult TransformError(global::System.Func<global::MyApp.FakeError, global::MyApp.FakeError> selector) => MapError(selector);
        
        public VoidResult RecoverWith(global::System.Func<global::MyApp.FakeError, VoidResult> fallback)
        {
            global::System.ArgumentNullException.ThrowIfNull(fallback);
            return _inner.IsSuccess ? this : fallback(_inner.Error);
        }
        public VoidResult OrElseThen(global::System.Func<global::MyApp.FakeError, VoidResult> fallback) => RecoverWith(fallback);
        
        public VoidResult OnSuccess(global::System.Action action)
        {
            global::System.ArgumentNullException.ThrowIfNull(action);
            return new(_inner.OnSuccess(_ => action()));
        }
        public VoidResult IfSuccessful(global::System.Action action) => OnSuccess(action);
        public VoidResult Tap(global::System.Action action) => OnSuccess(action);
        public VoidResult OnFailure(global::System.Action<global::MyApp.FakeError> action) => new(_inner.OnFailure(action));
        public VoidResult IfFailed(global::System.Action<global::MyApp.FakeError> action) => OnFailure(action);
        public VoidResult TapError(global::System.Action<global::MyApp.FakeError> action) => OnFailure(action);
        
        public TResult Match<TResult>(global::System.Func<TResult> onSuccess, global::System.Func<global::MyApp.FakeError, TResult> onFailure) => _inner.Match(_ => onSuccess(), onFailure);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> MapAsync<TNew>(global::System.Func<global::System.Threading.Tasks.Task<TNew>> selector)
        {
            global::System.ArgumentNullException.ThrowIfNull(selector);
            return _inner.MapAsync(_ => selector());
        }
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> TransformAsync<TNew>(global::System.Func<global::System.Threading.Tasks.Task<TNew>> selector) => MapAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> SelectAsync<TNew>(global::System.Func<global::System.Threading.Tasks.Task<TNew>> selector) => MapAsync(selector);
        public async global::System.Threading.Tasks.Task<VoidResult> BindAsync(global::System.Func<global::System.Threading.Tasks.Task<VoidResult>> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            if (_inner.IsSuccess)
            {
                return await next().ConfigureAwait(false);
            }
            if (_inner.IsFailure)
            {
                return Failure(_inner.Error);
            }
            throw new global::FuncyTown.ResultException("Cannot BindAsync an uninitialized Result.");
        }
        public global::System.Threading.Tasks.Task<VoidResult> ThenAsync(global::System.Func<global::System.Threading.Tasks.Task<VoidResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<VoidResult> AndThenAsync(global::System.Func<global::System.Threading.Tasks.Task<VoidResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<VoidResult> SelectManyAsync(global::System.Func<global::System.Threading.Tasks.Task<VoidResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> BindAsync<TNew>(global::System.Func<global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            return _inner.BindAsync(_ => next());
        }
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> ThenAsync<TNew>(global::System.Func<global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            return _inner.BindAsync(_ => next());
        }
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> AndThenAsync<TNew>(global::System.Func<global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            return _inner.BindAsync(_ => next());
        }
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> SelectManyAsync<TNew>(global::System.Func<global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            return _inner.BindAsync(_ => next());
        }
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::FuncyTown.Unit, TNewError>> MapErrorAsync<TNewError>(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TNewError>> selector) => _inner.MapErrorAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<global::FuncyTown.Unit, TNewError>> TransformErrorAsync<TNewError>(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TNewError>> selector) => MapErrorAsync(selector);
        public async global::System.Threading.Tasks.Task<VoidResult> MapErrorAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.FakeError>> selector)
        {
            return new(await _inner.MapErrorAsync(selector).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<VoidResult> TransformErrorAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.FakeError>> selector) => MapErrorAsync(selector);
        public async global::System.Threading.Tasks.Task<VoidResult> RecoverWithAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<VoidResult>> fallback)
        {
            global::System.ArgumentNullException.ThrowIfNull(fallback);
            if (_inner.IsSuccess)
            {
                return this;
            }
            if (_inner.IsFailure)
            {
                return await fallback(_inner.Error).ConfigureAwait(false);
            }
            throw new global::FuncyTown.ResultException("Cannot RecoverWithAsync on an uninitialized Result.");
        }
        public global::System.Threading.Tasks.Task<VoidResult> OrElseThenAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<VoidResult>> fallback) => RecoverWithAsync(fallback);
        public async global::System.Threading.Tasks.Task<VoidResult> OnSuccessAsync(global::System.Func<global::System.Threading.Tasks.Task> action)
        {
            global::System.ArgumentNullException.ThrowIfNull(action);
            return new(await _inner.OnSuccessAsync(_ => action()).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<VoidResult> IfSuccessfulAsync(global::System.Func<global::System.Threading.Tasks.Task> action) => OnSuccessAsync(action);
        public global::System.Threading.Tasks.Task<VoidResult> TapAsync(global::System.Func<global::System.Threading.Tasks.Task> action) => OnSuccessAsync(action);
        public async global::System.Threading.Tasks.Task<VoidResult> OnFailureAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action)
        {
            return new(await _inner.OnFailureAsync(action).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<VoidResult> IfFailedAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action) => OnFailureAsync(action);
        public global::System.Threading.Tasks.Task<VoidResult> TapErrorAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action) => OnFailureAsync(action);
        public global::System.Threading.Tasks.Task<TResult> MatchAsync<TResult>(global::System.Func<global::System.Threading.Tasks.Task<TResult>> onSuccess, global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TResult>> onFailure)
        {
            global::System.ArgumentNullException.ThrowIfNull(onSuccess);
            global::System.ArgumentNullException.ThrowIfNull(onFailure);
            return _inner.MatchAsync(_ => onSuccess(), onFailure);
        }
        public override string ToString() => _inner.ToString();
        
        private sealed class VoidResultJsonConverter : global::System.Text.Json.Serialization.JsonConverter<VoidResult>
        {
            public override VoidResult Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
            {
                var result = global::System.Text.Json.JsonSerializer.Deserialize<global::FuncyTown.Result<global::FuncyTown.Unit, global::MyApp.FakeError>>(ref reader, options);
                if (result.IsSuccess)
                {
                    return VoidResult.Success();
                }
                
                if (result.IsFailure)
                {
                    return VoidResult.Failure(result.Error);
                }
                
                throw new global::System.Text.Json.JsonException("Cannot deserialize an uninitialized Result alias.");
            }
            
            public override void Write(global::System.Text.Json.Utf8JsonWriter writer, VoidResult value, global::System.Text.Json.JsonSerializerOptions options)
            {
                if (!value.IsSuccess && !value.IsFailure)
                {
                    throw new global::System.Text.Json.JsonException("Cannot serialize an uninitialized Result alias.");
                }
                
                var result = value.IsSuccess ? global::FuncyTown.Result<global::FuncyTown.Unit, global::MyApp.FakeError>.Success(global::FuncyTown.Unit.Value) : global::FuncyTown.Result<global::FuncyTown.Unit, global::MyApp.FakeError>.Failure(value.Error);
                global::System.Text.Json.JsonSerializer.Serialize(writer, result, options);
            }
        }
    }
}
