//HintName: MyApp_ExplicitResult.g.cs
// <auto-generated />
#nullable enable
#pragma warning disable CS1591

namespace MyApp
{
    [global::System.Text.Json.Serialization.JsonConverter(typeof(ExplicitResult.ExplicitResultJsonConverter))]
    public readonly partial record struct ExplicitResult
    {
        private readonly global::FuncyTown.Result<int, global::MyApp.FakeError> _inner;
        
        private ExplicitResult(global::FuncyTown.Result<int, global::MyApp.FakeError> inner) : this() => _inner = inner;
        
        public static ExplicitResult Success(int value) => new(global::FuncyTown.Result<int, global::MyApp.FakeError>.Success(value));
        public static ExplicitResult Failure(global::MyApp.FakeError error) => new(global::FuncyTown.Result<int, global::MyApp.FakeError>.Failure(error));
        
        public bool IsSuccess => _inner.IsSuccess;
        public bool IsFailure => _inner.IsFailure;
        public int Value => _inner.Value;
        public global::MyApp.FakeError Error => _inner.Error;
        
        public void Deconstruct(out bool isSuccess, out int? value, out global::MyApp.FakeError? error)
        {
            isSuccess = _inner.IsSuccess;
            value = _inner.IsSuccess ? _inner.Value : default;
            error = _inner.IsFailure ? _inner.Error : default;
        }
        
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Map<TNew>(global::System.Func<int, TNew> selector) => _inner.Map(selector);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Transform<TNew>(global::System.Func<int, TNew> selector) => Map(selector);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Select<TNew>(global::System.Func<int, TNew> selector) => Map(selector);
        
        public ExplicitResult Bind(global::System.Func<int, ExplicitResult> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            return _inner.IsSuccess ? next(_inner.Value) : Failure(_inner.Error);
        }
        public ExplicitResult Then(global::System.Func<int, ExplicitResult> next) => Bind(next);
        public ExplicitResult AndThen(global::System.Func<int, ExplicitResult> next) => Bind(next);
        public ExplicitResult SelectMany(global::System.Func<int, ExplicitResult> next) => Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Bind<TNew>(global::System.Func<int, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> Then<TNew>(global::System.Func<int, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> AndThen<TNew>(global::System.Func<int, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(next);
        public global::FuncyTown.Result<TNew, global::MyApp.FakeError> SelectMany<TNew>(global::System.Func<int, global::FuncyTown.Result<TNew, global::MyApp.FakeError>> next) => _inner.Bind(next);
        
        public global::FuncyTown.Result<int, TNewError> MapError<TNewError>(global::System.Func<global::MyApp.FakeError, TNewError> selector) => _inner.MapError(selector);
        public global::FuncyTown.Result<int, TNewError> TransformError<TNewError>(global::System.Func<global::MyApp.FakeError, TNewError> selector) => MapError(selector);
        public ExplicitResult MapError(global::System.Func<global::MyApp.FakeError, global::MyApp.FakeError> selector) => new(_inner.MapError(selector));
        public ExplicitResult TransformError(global::System.Func<global::MyApp.FakeError, global::MyApp.FakeError> selector) => MapError(selector);
        
        public ExplicitResult Recover(global::System.Func<global::MyApp.FakeError, int> fallback) => new(_inner.Recover(fallback));
        public ExplicitResult OrElse(global::System.Func<global::MyApp.FakeError, int> fallback) => Recover(fallback);
        public ExplicitResult RecoverWith(global::System.Func<global::MyApp.FakeError, ExplicitResult> fallback)
        {
            global::System.ArgumentNullException.ThrowIfNull(fallback);
            return _inner.IsSuccess ? this : fallback(_inner.Error);
        }
        public ExplicitResult OrElseThen(global::System.Func<global::MyApp.FakeError, ExplicitResult> fallback) => RecoverWith(fallback);
        public ExplicitResult Ensure(global::System.Func<int, bool> predicate, global::MyApp.FakeError error) => new(_inner.Ensure(predicate, error));
        public ExplicitResult Validate(global::System.Func<int, bool> predicate, global::MyApp.FakeError error) => Ensure(predicate, error);
        
        public ExplicitResult OnSuccess(global::System.Action<int> action) => new(_inner.OnSuccess(action));
        public ExplicitResult IfSuccessful(global::System.Action<int> action) => OnSuccess(action);
        public ExplicitResult Tap(global::System.Action<int> action) => OnSuccess(action);
        public ExplicitResult OnFailure(global::System.Action<global::MyApp.FakeError> action) => new(_inner.OnFailure(action));
        public ExplicitResult IfFailed(global::System.Action<global::MyApp.FakeError> action) => OnFailure(action);
        public ExplicitResult TapError(global::System.Action<global::MyApp.FakeError> action) => OnFailure(action);
        
        public TResult Match<TResult>(global::System.Func<int, TResult> onSuccess, global::System.Func<global::MyApp.FakeError, TResult> onFailure) => _inner.Match(onSuccess, onFailure);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> MapAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<TNew>> selector) => _inner.MapAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> TransformAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<TNew>> selector) => MapAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> SelectAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<TNew>> selector) => MapAsync(selector);
        public async global::System.Threading.Tasks.Task<ExplicitResult> BindAsync(global::System.Func<int, global::System.Threading.Tasks.Task<ExplicitResult>> next)
        {
            global::System.ArgumentNullException.ThrowIfNull(next);
            if (_inner.IsSuccess)
            {
                return await next(_inner.Value).ConfigureAwait(false);
            }
            if (_inner.IsFailure)
            {
                return Failure(_inner.Error);
            }
            throw new global::FuncyTown.ResultException("Cannot BindAsync an uninitialized Result.");
        }
        public global::System.Threading.Tasks.Task<ExplicitResult> ThenAsync(global::System.Func<int, global::System.Threading.Tasks.Task<ExplicitResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<ExplicitResult> AndThenAsync(global::System.Func<int, global::System.Threading.Tasks.Task<ExplicitResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<ExplicitResult> SelectManyAsync(global::System.Func<int, global::System.Threading.Tasks.Task<ExplicitResult>> next) => BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> BindAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> ThenAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> AndThenAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>> SelectManyAsync<TNew>(global::System.Func<int, global::System.Threading.Tasks.Task<global::FuncyTown.Result<TNew, global::MyApp.FakeError>>> next) => _inner.BindAsync(next);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<int, TNewError>> MapErrorAsync<TNewError>(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TNewError>> selector) => _inner.MapErrorAsync(selector);
        public global::System.Threading.Tasks.Task<global::FuncyTown.Result<int, TNewError>> TransformErrorAsync<TNewError>(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TNewError>> selector) => MapErrorAsync(selector);
        public async global::System.Threading.Tasks.Task<ExplicitResult> MapErrorAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.FakeError>> selector)
        {
            return new(await _inner.MapErrorAsync(selector).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<ExplicitResult> TransformErrorAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<global::MyApp.FakeError>> selector) => MapErrorAsync(selector);
        public async global::System.Threading.Tasks.Task<ExplicitResult> RecoverAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<int>> fallback)
        {
            return new(await _inner.RecoverAsync(fallback).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<ExplicitResult> OrElseAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<int>> fallback) => RecoverAsync(fallback);
        public async global::System.Threading.Tasks.Task<ExplicitResult> RecoverWithAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<ExplicitResult>> fallback)
        {
            global::System.ArgumentNullException.ThrowIfNull(fallback);
            if (_inner.IsSuccess)
            {
                return this;
            }
            if (_inner.IsFailure)
            {
                return await fallback(_inner.Error).ConfigureAwait(false);
            }
            throw new global::FuncyTown.ResultException("Cannot RecoverWithAsync on an uninitialized Result.");
        }
        public global::System.Threading.Tasks.Task<ExplicitResult> OrElseThenAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<ExplicitResult>> fallback) => RecoverWithAsync(fallback);
        public async global::System.Threading.Tasks.Task<ExplicitResult> EnsureAsync(global::System.Func<int, global::System.Threading.Tasks.Task<bool>> predicate, global::MyApp.FakeError error)
        {
            return new(await _inner.EnsureAsync(predicate, error).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<ExplicitResult> ValidateAsync(global::System.Func<int, global::System.Threading.Tasks.Task<bool>> predicate, global::MyApp.FakeError error) => EnsureAsync(predicate, error);
        public async global::System.Threading.Tasks.Task<ExplicitResult> OnSuccessAsync(global::System.Func<int, global::System.Threading.Tasks.Task> action)
        {
            return new(await _inner.OnSuccessAsync(action).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<ExplicitResult> IfSuccessfulAsync(global::System.Func<int, global::System.Threading.Tasks.Task> action) => OnSuccessAsync(action);
        public global::System.Threading.Tasks.Task<ExplicitResult> TapAsync(global::System.Func<int, global::System.Threading.Tasks.Task> action) => OnSuccessAsync(action);
        public async global::System.Threading.Tasks.Task<ExplicitResult> OnFailureAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action)
        {
            return new(await _inner.OnFailureAsync(action).ConfigureAwait(false));
        }
        public global::System.Threading.Tasks.Task<ExplicitResult> IfFailedAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action) => OnFailureAsync(action);
        public global::System.Threading.Tasks.Task<ExplicitResult> TapErrorAsync(global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task> action) => OnFailureAsync(action);
        public global::System.Threading.Tasks.Task<TResult> MatchAsync<TResult>(global::System.Func<int, global::System.Threading.Tasks.Task<TResult>> onSuccess, global::System.Func<global::MyApp.FakeError, global::System.Threading.Tasks.Task<TResult>> onFailure) => _inner.MatchAsync(onSuccess, onFailure);
        public override string ToString() => _inner.ToString();
        
        private sealed class ExplicitResultJsonConverter : global::System.Text.Json.Serialization.JsonConverter<ExplicitResult>
        {
            public override ExplicitResult Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
            {
                var result = global::System.Text.Json.JsonSerializer.Deserialize<global::FuncyTown.Result<int, global::MyApp.FakeError>>(ref reader, options);
                if (result.IsSuccess)
                {
                    return ExplicitResult.Success(result.Value);
                }
                
                if (result.IsFailure)
                {
                    return ExplicitResult.Failure(result.Error);
                }
                
                throw new global::System.Text.Json.JsonException("Cannot deserialize an uninitialized Result alias.");
            }
            
            public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ExplicitResult value, global::System.Text.Json.JsonSerializerOptions options)
            {
                if (!value.IsSuccess && !value.IsFailure)
                {
                    throw new global::System.Text.Json.JsonException("Cannot serialize an uninitialized Result alias.");
                }
                
                var result = value.IsSuccess ? global::FuncyTown.Result<int, global::MyApp.FakeError>.Success(value.Value) : global::FuncyTown.Result<int, global::MyApp.FakeError>.Failure(value.Error);
                global::System.Text.Json.JsonSerializer.Serialize(writer, result, options);
            }
        }
    }
}
